### ISSUE TITLE
ForgeHax not loading into Forge

### ISSUE THREAD

**Issue by mdino24** [fr1kin/ForgeHax#101]
When forge started says "ForgeHax is for an older version of forge and cannot be loaded" pls fix or help
![forgeHax](https://user-images.githubusercontent.com/53289119/61848625-b5283680-ae7c-11e9-8858-25c41ef1e775.png)

**Comment by fr1kin** [comment]
What version of forge are you running?

**Comment by mdino24** [comment]
> What version of forge are you running?

Im running the newest one 1.14.4
and the newest link for ForgeHax

**Comment by VADemon** [comment]
You are right, here's no Forgehax for 1.14
![112](https://user-images.githubusercontent.com/1168140/61881728-6d92c080-aef7-11e9-85f1-2011972fe1a2.png)

**Comment by mdino24** [comment]
So what should i do?

**Comment by 0-x-2-2** [comment]
nothing
