### ISSUE TITLE
download no work

### ISSUE THREAD

**Issue by legencosmic** [fr1kin/ForgeHax#102]
hi i want to download forgehax and im on mac but when i open it it comes up with a error

**Comment by wifebeater** [comment]
cringe

**Comment by wifebeater** [comment]
🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡

**Comment by fr1kin** [comment]
int -1
