### ISSUE TITLE
Step off of chests

### ISSUE THREAD

**Issue by LoganDark** [fr1kin/ForgeHax#111]
This issue is related to #109.

You can't step up from chests, you have to jump.

This could be solved by making the step height slightly higher, like 1.1.

**Comment by LoganDark** [comment]
you can't even step up from paths...

**Comment by fr1kin** [comment]
never did this because NCP would flag you, and since 2b2t is the only server i play it was good enough for me

**Comment by bowwychan** [comment]
>2b2t
>good server
🤡

**Comment by LoganDark** [comment]
@fr1kin you have a hack for 1, players can jump off of chests so can't you tweak the bypass code?

**Comment by fr1kin** [comment]
I am not sure how well the bypass code even works now days, if at all. It was a dumb hack to begin with that would trigger too many packets checks eventually.

**Comment by LoganDark** [comment]
Well, I could remove the code in #113 if you'd like. Besides, most anticheats detect step now anyway, I think it's time to drop that hack if there's no better solution.

**Comment by fr1kin** [comment]
No reason to delete it as it can be used in servers without anticheats.

**Comment by LoganDark** [comment]
You can fly in servers without anticheats. You don't need to fake packets like that. I was more hinting at the fact that it's hardcoded for 1 and 1.5...

**Comment by fr1kin** [comment]
My mindset when adding features in forgehax is what I want, not necessarily what others want. When I originally added step, it was because I wanted to walk up stairs in the nether on 2b2t faster. This is generally the same mindset I have for every feature I add.

**Comment by LoganDark** [comment]
Then I won't remove the bypass. It does only kick in when it needs to, so it won't mess up with bigger step values. I've already made a pull request, and you can click a button to add this feature to ForgeHax. It will slightly tweak _your_ step value from 1.0 to 1.2, to allow you to step up from paths and chests. It's a single command to change this back, and it's a good QoL change, in my opinion. Of course, I'm always at your mercy when it comes to things like this, but I don't see a single downside right now.

**Comment by LoganDark** [comment]
Fixed by the #113 merge
