### ISSUE TITLE
Update mappings

### ISSUE THREAD

**Issue by LoganDark** [fr1kin/ForgeHax#115]
You're using MCP mappings from 2017. `stable_39` is the latest 1.12.2 mapping. It's a lot newer and also marked stable.

Curious to hear why you're staying on these old mappings, as I'm sure you have a good reason

**Comment by fr1kin** [comment]
>Curious to hear why you're staying on these old mappings, as I'm sure you have a good reason

"If its not broke don't fix it"

**Comment by LoganDark** [comment]
If I created a PR for this, then would you merge it?

**Comment by fr1kin** [comment]
If you verify it works in production

**Comment by LoganDark** [comment]
Yes, I will. Jenkins builds it automatically so when I make the PR I will check.

**Comment by fr1kin** [comment]
I use 1.12.2-14.23.5.2775. I think newer versions of forge don't work with forgehax, but I don't remember.

**Comment by LoganDark** [comment]
2838 here

**Comment by fr1kin** [comment]
Technically forgehax does have a 1.13.2 build. @babbaj maintains it (somewhat) so that when 2b2t updates to 1.13 we will be ready.

**Comment by LoganDark** [comment]
Well, that's their problem then. This probably won't affect them, correct me if I'm wrong.

**Comment by LoganDark** [comment]
So, I kind of stuck a Forge MDK in the ForgeHax directory to see if it would work. Clearly it didn't. While on the topic of mappings, since my build fails trying to find `http://export.mcpbot.bspk.rs/mcp/@forgehax.mcp.version@/mcp-@forgehax.mcp.version@-srg.zip` (which I know is an formatting error), exactly what build system am I supposed to use for this, if not ForgeGradle?

**Comment by fr1kin** [comment]
Yeah this is some dumb issue caused because the gradle build doesn't apply the tokens to config.properties. A simple fix is to run gradle build, then find the conf.properties in the `build/resources` directory and copy/replace it to `out/production/.../resources/config.properties`

**Comment by LoganDark** [comment]
Aw fuck, it was that issue you outlined in the FAQ. You should specify which exception that causes...

**Comment by fr1kin** [comment]
Sorry about that. It's a really weird bug because sometimes it works, but other times it doesn't. In another project of mine, I wrote something that manually applies the tokens to config.properties if it detects its running in an IDE.

**Comment by LoganDark** [comment]
Well another weird bug is that after doing all sorts of weird stuff to try to get IntelliJ to load the project properly, ForgeHax ASM loads but not ForgeHax itself.

![image](https://user-images.githubusercontent.com/4723091/63404256-59779d00-c397-11e9-9c78-20f30770d6fd.png)

Do you have a Discord so we could talk there instead of over GitHub issues? since this is getting a little off topic

**Comment by fr1kin** [comment]
fr1kin#8565

**Comment by fr1kin** [comment]
I use the latest forge 1.12.2 release now, but I kept the mappings the same as forge hasn't updated them either. Just gonna keep it at that.
