### ISSUE TITLE
EditorConfig

### ISSUE THREAD

**Issue by LoganDark** [fr1kin/ForgeHax#116]
Your project uses some funky formatting, including using spaces as indentation, you should use an EditorConfig file so I don't need to taint my IDE with that kind of explicit configuration.

**Comment by fr1kin** [comment]
I tried to enforce spacing standards using Spotless, but that fell apart because it started making some code look extremely hideous. Good idea though.

**Comment by LoganDark** [comment]
Indentation is the main concern here. 2 for classes, 4 for functions, I guess? Does EC even support that?

**Comment by fr1kin** [comment]
No clue, first time I have heard about it. I would like to enforce some code quality though. One project I contributed too had a git pre commit hook that ran a code prettier to enforce some spacing and other standards.

**Comment by LoganDark** [comment]
> git pre commit hook that ran a code prettier

That sounds hilarious and terrifying at the same time.

**Comment by fr1kin** [comment]
I actually think it is a good idea. One big issue with spotless is that I would always forget to run spotless before commiting changes and mindlessly pushing, causing the build to fail (spotless will fail builds that aren't up to standard). Git hooks would fix that. Just need to re-add the gradle wrapper to this project so the git hook can execute gradlew.

**Comment by LoganDark** [comment]
If you use EditorConfig, your editor will use the correct formatting!

IntelliJ automatically reads from EditorConfig, and can effortlessly reformat the file with a single keypress. I use it all the time when editing files. I always hit reformat before saving.

**Comment by babbaj** [comment]
im pretty sure theres is both code indented with 2 spaces and code indented with 4 spaces

**Comment by fr1kin** [comment]
the ultimate pozpill
