### ISSUE TITLE
More information about the modules

### ISSUE THREAD

**Issue by ClemGlacee** [fr1kin/ForgeHax#128]
There are a lot of modules I don't really know so I don't get what they do exactly or even if they are useful for what I want to do. What would be nice is a little description in the gui when you hover each module so you know exactly what they do and how to use them.

**Comment by LoganDark** [comment]
> a little description in the gui when you hover each module

Yes, all the yes. Each mod already has a description. I was already planning on putting this in a PR, but now I have an issue to tie it to. Thank you.

**Comment by babbaj** [comment]
>gui

🤡
