### ISSUE TITLE
text file not loading after .book file *text file name*

### ISSUE THREAD

**Issue by Wilksey123** [fr1kin/ForgeHax#133]
i use this with forge hax to the commands for me are .book not .bookbot

so i do .book file Chapter One.txt 
which is the file i want to write, then it says its found the file
then when i do 
.book load Chapter One.txt it says file not found

**Comment by Wilksey123** [comment]
Issue solved, cant have spaces in the text file name

**Comment by fr1kin** [comment]
should be `.book file "Chapter One.txt"` if you have spaces
