### ISSUE TITLE
How do i move the activemods list to a different corner?

### ISSUE THREAD

**Issue by Audition-CSBlock** [fr1kin/ForgeHax#140]
Im using impact and forgehax at the same time and theyre in the way of eachother, would it be possible to move the list to the left-bottom corner?

**Comment by VADemon** [comment]
Currently not possible, no. You can disable `.activem en 0` for the time being.

Leave the issue open.

**Comment by Audition-CSBlock** [comment]
@VADemon I have another question, how do i disable the "Command input" on the title screen?

**Comment by fr1kin** [comment]
Not possible

**Comment by Quazar5** [comment]
Is this possible to do in the config?  Disable the active mod list, I mean.

**Comment by fr1kin** [comment]
Yes. Read the FAQ or the wiki.

**Comment by VADemon** [comment]
Options updated in the wiki: https://github.com/fr1kin/ForgeHax/wiki/ActiveMods

![alignment](https://user-images.githubusercontent.com/1168140/70493331-995dbe00-1b07-11ea-976c-8f8f1110c8ea.jpg)
