### ISSUE TITLE
Click Gui

### ISSUE THREAD

**Issue by barrythebogan** [fr1kin/ForgeHax#149]
How do i rebind the click Gui?

**Comment by VADemon** [comment]
It's under normal Minecraft options → Controls → Forgehax. iirc either "Open Gui" or "GUI"

**Comment by fr1kin** [comment]
I believe there should be a bind entry under Controls in your Minecraft settings. Should be named _ForgeHax GUI_ or just _GUI_

**Comment by barrythebogan** [comment]
thank you
