### ISSUE TITLE
markers help?

### ISSUE THREAD

**Issue by khoopa** [fr1kin/ForgeHax#158]
I can enable markers but nothing shows up, I add Obsidian using .markers options add obsidian -r 250 -g 230 -b 150 but nothing shows.

**Comment by VADemon** [comment]
Other installed mods may interfere. Try on a clean instance to make sure your commands are in fact correct.

**Comment by khoopa** [comment]
Command is correct, tested without mods, iron ore lights up as colour specified. I don't know what seems to be interfering since there's about a hundred plus mods.

**Comment by VADemon** [comment]
Well... yes. Forge-mod Xray was interfering for me. Any chunk/core rendering mod could cause problems too.

Meanwhile you can try Xray-DLB (iirc): it caused problems for FH but worked.

**Comment by khoopa** [comment]
fullbright also seems to have some interference with mods in the modpack, I'll check out Xray-DLB then
