### ISSUE TITLE
Any chance to get this to work on 1.14.4 ?

### ISSUE THREAD

**Issue by Johnny112233** [fr1kin/ForgeHax#159]

**Comment by fr1kin** [comment]
Updating the 1.13 branch to 1.14.4 would be the easiest, but unless you have the skills necessary it won't be easy.

**Comment by Johnny112233** [comment]
Okay. Unfortunately I think I don't have these skills.

Are you aware of any other Autoplace mod that works on 1.14.4 ?
It's the feature I need ForgeHax for. Can't find it anywhere else.

**Comment by fr1kin** [comment]
Schematica or Baritone

**Comment by ImRaddar** [comment]
yeah add 1.14.4 support kthx
