### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by omerbadawy11** [fr1kin/ForgeHax#178]
i get his error when i launch my game with forgehax included
https://paste.dimdev.org/ederiqiyoq.mccrash
![image](https://user-images.githubusercontent.com/16752592/77556966-1dd81f00-6ef4-11ea-9010-6ba73699fd17.png)

Could i please i get any help with this?

thank you,
have a great day

**Comment by starcraft66** [comment]
Please upload the contents of the file highlighted in green here.

**Comment by babbaj** [comment]
looks like an incompatibility caused by this awful hook 
https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/asm/patches/RenderChunkPatch.java

**Comment by omerbadawy11** [comment]
> 
> 
> looks like an incompatibility caused by this awful hook
> https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/asm/patches/RenderChunkPatch.java

Is there a way for me to do something to avoid it? i would really appreciate any help.
thank you!

**Comment by babbaj** [comment]
> > looks like an incompatibility caused by this awful hook
> > https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/asm/patches/RenderChunkPatch.java
> 
> Is there a way for me to do something to avoid it? i would really appreciate any help.
> thank you!

just comment out the @Inject and recompile

**Comment by omerbadawy11** [comment]
> 
> 
> > > looks like an incompatibility caused by this awful hook
> > > https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/asm/patches/RenderChunkPatch.java
> > 
> > 
> > Is there a way for me to do something to avoid it? i would really appreciate any help.
> > thank you!
> 
> just comment out the @Inject and recompile

Sorry, i have no idea how to do that... Guess ill move on. but thank you for all your help, have a great day :)
