### ISSUE TITLE
[1.15] Binding certain keys causes game to crash

### ISSUE THREAD

**Issue by Thedeur** [fr1kin/ForgeHax#181]
Minecraft Version 1.15.2
Forge Version 31.1.0

Upon binding certain keys in the key config menu, namely **MOUSE4/5**, the game crashes, and upon restart can't load any option (Singleplayer, Options) without crashing again. 

To render the game functional again with ForgeHax enabled requires you to: 

1. Disable the mod
2. Launch MC, go into the controls/world where the settings were fiddled with
3. Exit MC
4. Re-enable FH

At which point it _should_ launch okay again, with the keybinding forgotten.

**Comment by fr1kin** [comment]
Mind sending your latest.log?

**Comment by Thedeur** [comment]
[Here you go.](https://github.com/fr1kin/ForgeHax/files/4406154/latest_scrubbed.log)

**Comment by fr1kin** [comment]
Thanks
