### ISSUE TITLE
AutoPlace issue with NBT data

### ISSUE THREAD

**Issue by E1ZY** [fr1kin/ForgeHax#188]
For example you can't choose two or more colors of carpet to place because it is removing it from the list when you trying do it.

**Comment by fr1kin** [comment]
1.12.2 or 1.15.2?

**Comment by E1ZY** [comment]
1.12.2

**Comment by E1ZY** [comment]
Probably something wrong with UniqueBlock class

**Comment by fr1kin** [comment]
Yeah there is a problem with ForgeHax 1.12.2 in general lol. I will see what I can do about it

**Comment by E1ZY** [comment]
nvm, I am an idiot. it is working fine
