### ISSUE TITLE
Causes a crash with tekxit 3.

### ISSUE THREAD

**Issue by OFWModz** [fr1kin/ForgeHax#189]
No point explaining, it's pretty simple.

Simply drop it into %appdata%\.technic\modpacks\tekxit-3-official-1122\mods\ using technic launcher to get tekxit 3 in the first place.

Would be really nice to have fixed.

**Comment by fr1kin** [comment]
Mind providing your debug.log?

**Comment by OFWModz** [comment]
https://www.dropbox.com/s/zhteus8ajfgqvkb/logs.zip?dl=1

**Comment by fr1kin** [comment]
Looks like its the RenderChunksPatch I have for Markers. I won't fix it on the main branch, but you can easily get a working version of ForgeHax by cloning the repo and building the project yourself. You just need to comment out the line with `new RenderChunkPatch()` in ForgeHaxTransformer.java, then run:
`./gradlew setupDecompWorkspace && ./gradlew build` (if you are on windows replace `./gradlew` with `./gradlew.bat`)

**Comment by OFWModz** [comment]
Why not make a secondary branch for major mod compat such as for modpacks like tekxit? Ideally with releases to save people's time.

**Comment by fr1kin** [comment]
I probably could make the gradle build produce two artifacts - a normal jar, and another jar that excludes the marker patches. I will think about it, but it would be a tad difficult seeing as I would have to make the task remove a couple lines of code.

**Comment by OFWModz** [comment]
If you do set that up I will actively test for bugs if needed.

The reason I refuse to build it for myself is I'm a lazy dev too. You know the feels. Cba mofo xD
