### ISSUE TITLE
ActiveMods list bug

### ISSUE THREAD

**Issue by OFWModz** [fr1kin/ForgeHax#191]
Upon setting ActiveMods.enabled to false, it cannot be set back to true.

![image](https://user-images.githubusercontent.com/36628963/79301319-3b8c1900-7ee1-11ea-8949-68e3b15aa605.png)

**Comment by fr1kin** [comment]
You don't need to add the `=`. Just do `activemods enabled true`

**Comment by OFWModz** [comment]
Using it to set it to false worked, but not true. I would make the client globally recognise both as being a coder I can't help it. xD

**Comment by fr1kin** [comment]
Yes the parser will check if the argument matches t(rue), 1, on, or e(nabled)

**Comment by OFWModz** [comment]
Yet it never worked there but did without the =.
