### ISSUE TITLE
[15.2] NoSuchMethodError

### ISSUE THREAD

**Issue by Mr-Kon** [fr1kin/ForgeHax#195]
When I launch the game I get this error while using forgemod 31.1.0 and forgehax 15.2.-3.0.0
I have no idea why, I installed both normaly.
[crash-2020-04-20_22.53.55-client.txt](https://github.com/fr1kin/ForgeHax/files/4508025/crash-2020-04-20_22.53.55-client.txt)

**Comment by fr1kin** [comment]
Try updating forge

**Comment by Mr-Kon** [comment]
updated to 31.1.47 and got a new error "The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.util.registry.Registry"
[crash-2020-04-20_23.25.38-client.txt](https://github.com/fr1kin/ForgeHax/files/4508067/crash-2020-04-20_23.25.38-client.txt)

**Comment by fr1kin** [comment]
try using https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.2-31.1.30/forge-1.15.2-31.1.30-installer.jar

**Comment by Mr-Kon** [comment]
I got the same error as the first time but it got closer to launch 100% which is weird.

**Comment by fr1kin** [comment]
That's really weird. Are you using any other mods? I don't see why forgehax would be causing this issue. Can you remove forgehax from the mods folder and tell me if you still crash with the same error?

**Comment by Mr-Kon** [comment]
I think I was looking at the wrong log file, I think this might be the real problem
[23:53:16][ERROR][ForgeHax][modloading-worker-1][ForgeHax$ConfigProperties::<init>@136]: Could not find resource config.properties

**Comment by VADemon** [comment]
No this is normal flow. You have optifine enabled though

My log:
```
[m[32m[07:00:11] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[m[1;31m[07:00:11] [modloading-worker-4/ERROR] [de.fi.fo.ma.ForgeHax/]: Could not find resource config.properties
[m[33m[07:00:12] [modloading-worker-4/WARN] [de.fi.fo.ma.ForgeHax/]: plugin directory "....\MultiMC\instances\fh\.minecraft\forgehax\plugins" does not exist!
[m[32m[07:00:12] [modloading-worker-4/INFO] [de.fi.fo.ma.ForgeHax/]: No plugins loaded (this is fine)
[m[32m[07:00:13] 
```

**Comment by fr1kin** [comment]
That actually isn't an issue, or atleast it shouldn't be. The config.properties file isn't even really used anymore.

**Comment by Mr-Kon** [comment]
you are right, I removed every mod except forgehax and it now everything works fine.

**Comment by fr1kin** [comment]
Did you have optifine? Optifine doesn't officially support forge yet iirc

**Comment by Mr-Kon** [comment]
I did
