### ISSUE TITLE
Tracers

### ISSUE THREAD

**Issue by plasmame123** [fr1kin/ForgeHax#196]
typing the command ".tracers drawLines 1" says the command is unknown

**Comment by VADemon** [comment]
The bare minimum: mc and fh version? Do any other commands work?

**Comment by fr1kin** [comment]
Isn't it `tracers mode 2`?

**Comment by VADemon** [comment]
\>\.\> https://github.com/fr1kin/ForgeHax/commit/be284a9fd1626b5867aae77cebb959c2c2e5b00f

Yes, I didn't look at commits back then. [Wiki updated with up-to-date commands](https://github.com/fr1kin/ForgeHax/wiki/Tracers).

FYI you can bring up the command help for the mod by typing `.tracers` - it will show all available commands, not need to 100% rely on the wiki. ... and if you notice something like this again, you can edit the wiki too \**unambiguous wink*\*

/closed
