### ISSUE TITLE
Not compiling on my Mac

### ISSUE THREAD

**Issue by ili-codes** [fr1kin/ForgeHax#2]
Hey fr1kin, I've tried compiling ForgeHax with gradle, and it seems to throw an error. I'm pretty new to gradle so I'm not sure of the error.

Error:
![https://puu.sh/wi9zS/e281c318e0.png](https://puu.sh/wi9zS/e281c318e0.png)

A full log is [here](https://gist.githubusercontent.com/ili-codes/022381e0657ee7574d8f537c15eb1f1f/raw/eaebf08bfde911ed3daa99bb89686a2492517721/forgehax-compile-error.txt).

Thanks!

**Comment by ili-codes** [comment]
What is this error and how can I fix it?

**Comment by fr1kin** [comment]
have you run setupDecompWorkspace?

**Comment by fr1kin** [comment]
oh it seems you are missing journeymap. read the readme for instructions on where to download it and put it. i might have also messed something up in my latest commits. I will get to correcting everything tomorrow

**Comment by ili-codes** [comment]
thanks :)

**Comment by ili-codes** [comment]
Yep. Sure enough, I re-compiled with journeymap. It works. Thanks!
