### ISSUE TITLE
Bypass the screen share.

### ISSUE THREAD

**Issue by Shing172** [fr1kin/ForgeHax#203]
I changed the name of the .jar file, but when I enter the game, Forge's "mod button" still shows the name "ForgeHax". Is there any way to change that? I would like to bypass screen shares
![aa](https://user-images.githubusercontent.com/65086386/81481227-dc31d800-9204-11ea-90c4-cacde5c198e6.png)

**Comment by VADemon** [comment]
Disable all mods, `.activemods en 0` and to clear chat: `.clear`

And give more information if you want a discussion.

**Comment by Shing172** [comment]
> Disable all mods, `.activemods en 0` and to clear chat: `.clear`
> 
> And give more information if you want a discussion.

Sorry, I'm new at GitHub, I accidentally hit Enter and created the threadh.

**Comment by fr1kin** [comment]
Don't cheat on servers that don't allow it
