### ISSUE TITLE
help me not be detected

### ISSUE THREAD

**Issue by Serapius** [fr1kin/ForgeHax#211]
I have a problem, there is a server that I want to enter with ForgeHax, but when I do they see that I have it installed with a function that shows all the mods that I have installed to the owner. I wanted to know if there is any way to change the internal name of ForgeHax to another so as not to be detected. sorry for my bad english

**Comment by VADemon** [comment]
Hm I think the modname is only read from `mcmod.info` file. It's in the jar of any Forge mod.

Another way is to compile Forgehax yourself using gradle. There's a hidden extra for this effort.

**Comment by Serapius** [comment]
How do I run ForgeHax with Gradle?

**Comment by fr1kin** [comment]
`./gradlew setupDecompWorkspace && ./gradlew build` in the terminal. If you are using windows add `.bat` to the end of `./gradlew`
