### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by jeffgmy** [fr1kin/ForgeHax#218]
I followed all your directions exactly.  Download Latest 1.15.2 - 31.2.19 of Forge website.
Downloaded latest Hax: forgehax-1.12.2-2.9.0.jar
Put the Hax mod in my mod folder, run loader under Forge profile and I get this error message
![image](https://user-images.githubusercontent.com/66854847/84556483-089faf00-acf1-11ea-9042-17e20f127009.png)

**Comment by VADemon** [comment]
1.12.2 doesn't look right on 1.15 Minecraft, does it?

https://jenkins.nhackindustries.com/job/ForgeHax/job/1.15/lastSuccessfulBuild/artifact/build/libs/

The banners at the top of the readme are correct, but the text below isn't.
