### ISSUE TITLE
Flight is killing me.

### ISSUE THREAD

**Issue by atheran2** [fr1kin/ForgeHax#221]
Playing a single player modded world with a huge amount of mods. Enabling flight almost instantly kills the character even without moving and the graves are spawned at build height limit for some reason. I have no idea what's causing this so I posted in case someone knows how I can track down the issue.

I doubt it's the flight itself, as I was using Wurst for a few days and it's flight system didn't kill my character so it's probably some mod incompatibility that only exists with Forgehax.

**Comment by UltraBlackLinux** [comment]
Flight requires nofall. I think this may be a bug, that ur like flying, even on ground and u die from falldamage.

**Comment by atheran2** [comment]
Even with NoFall it kills me.

**Comment by UltraBlackLinux** [comment]
What is the Kill message?

**Comment by atheran2** [comment]
That I fell from very high or something along those lines. Not ingame right now to test.

**Comment by UltraBlackLinux** [comment]
Something seems to be messed up with nofall...

**Comment by fr1kin** [comment]
Nofall was modified to bypass NCP and I guess I broke vanilla nofall in the process

**Comment by atheran2** [comment]
It's not a big deal, just wanted to see what's going on. Also I noticed Baritone is becoming stupid with Forgehax. Say I put #mine iron_ore. It spends a long time searching for it and staying still even tho it has the green squares (goals) set. Once I move a few blocks towards a goal manually, it usually picks up by itself. And it happens with all ores, the iron was just an example.

That could be an issue with Baritone but it didn't happen when I was running Impact, Wurst or just Vanilla with Baritone. Just started happening now that I switched to Forgehax. Might be I'm using it wrong but however many times I went over the ForgeHax documentation, I have no idea what the Baritone button does and it has the pathing issue whether I turn it on or off (I have baritone as a seperate jar in my mods folder).

**Comment by UltraBlackLinux** [comment]
Then ask their Github.

**Comment by fr1kin** [comment]
That's weird, I don't see why forgehax would cause that to happen.

**Comment by UltraBlackLinux** [comment]
Huh? 
> Nofall was modified to bypass NCP and I guess I broke vanilla nofall in the process

**Comment by Jukelyn** [comment]
Flight does give fall damage, but if you were to go, for example, 20 blocks in the air and then go down 2 blocks to land on a block higher than you. There is no damage. If you were to fly up and just land at something else then it does hurt. It's weird to explain but basically, the higher you go, if you land you take damage unless you fly just below the block you want to land on, in which case there is no damage.

**Comment by Greeninja762** [comment]
sorry for the necro, but i also seem to be having this issue, except i take all fall damage, not the partial no-fall stuff that jukelyn was talking about. my friend is playing with the exact same version that i am and his nofall works perfectly fine.

**Comment by fr1kin** [comment]
I'll fix it tomorrow. Nofall was made to only work on ncp but since a lot of people seem to use it on vanilla I'll add a traditional nofall
