### ISSUE TITLE
Game doesn't load

### ISSUE THREAD

**Issue by Lotzym** [fr1kin/ForgeHax#223]
If I open my game in forge 1.15.2 without the forgehax.jar it works just fine, but with the forgehax loaded it just crashes before loading everything. In the console it says "(exit code -1)". I checked my Java and I have java 8 version 241. I don't know what to do.
The forge version is 31.2.23 and the forgehax is 3.0.0-570c475. Could someone help me please?

**Comment by fr1kin** [comment]
Can you try forge version 31.1.30?

**Comment by Lotzym** [comment]
I tried it and now this message pops up:

"Java Virtual Machine Launcher

Error: Could not create the Java Machine Launcher
Error: A fatal excpetion has occurred. Program will exit."

However, that was on the original mojang launcher, I tried it in a different pirate launcher and it worked just fine, so I guess that´s a win? Thanks a lot!

**Comment by VADemon** [comment]
Maybe the vanilla launcher doesn't give enough memory (-Xmx) for it to launch? This is weird. I believe there must be an error message somewhere in the logs, well...

**Comment by fr1kin** [comment]
It might also be an issue with that version of java. I couldn't get openjdk8 242 to work with anything minecraft related, had to downgrade to 232.

**Comment by CStafford-14** [comment]
Same issue, launching with MultiMC and Forge 31.2.33, running Java 8 251. (Doing this on Ubuntu 18.04 btw)

Basically, everything is completely fine up until the game window opens, then it immediately crashes.

I managed to roll back the Java8 version to 232, and I still get the same result.

Using ForgeHax-1.15.2-3.0.0-570c476

**Comment by fr1kin** [comment]
I think its because forge changed something in its mod loader, so my hack mod loader calls an invalid method. Try using the version of forge ForgeHax was built with.

**Comment by CStafford-14** [comment]
Which was...?

**Comment by fr1kin** [comment]
31.1.30

**Comment by CStafford-14** [comment]
Ok, it finally loads, but when I create/open a world, it puts me back at the main menu. It didn't crash, nor do I have anything like VanillaFix.
