### ISSUE TITLE
Doesn't Launch

### ISSUE THREAD

**Issue by wasse111** [fr1kin/ForgeHax#229]
This issue is very similar to issue #223 but its 1.12.2. My Game just don't launch with forgehax. When I launch the game without forgehax the game launches. I tried to reinstall java, downloading JDK 8 and 11 still doesn't work. Right now is my java version 1.8.0_251. The forge version is 14.23.5.2864

**Comment by VADemon** [comment]
Works for me with Forge 14.23.4.2705. Old MC doesn't launch at all with newer JDKs without additional launcher mods (hacks).

You'd need to provide the logs. There may be crash logs in `.minecraft` but the normal logs are in `.minecraft/logs/`

**Comment by wasse111** [comment]
Okay, this is my logs https://pastebin.com/1QkkqJQP

**Comment by fr1kin** [comment]
```
com.matt.forgehax.asm.utils.remapping.MCPMappingLoader$CantLoadMCPMappingException: Unable to find static_methods.txt. Your MCP conf folder may be corrupt.
```

Weird... the mappings files are corrupted. Try deleting `~/.cache/MCPMappingViewer`

**Comment by wasse111** [comment]
That worked! Thank you for helping me btw
