### ISSUE TITLE
Macros problem

### ISSUE THREAD

**Issue by Darko1green1LOrd** [fr1kin/ForgeHax#233]
i want to make macro to say on press #sudo ** v off  then  /v on  then /clearchat  then /op Darko_green_LOrd  im using .bindmacro "say #sudo ** v off" but it just says #sudo and the rest as commands when i do "say "#sudo ** v off"" it doesnt work

**Comment by Darko1green1LOrd** [comment]
oh i forgot i type .bindmacro l  and then the stuff

**Comment by Darko1green1LOrd** [comment]
i also tried to modify its cfg after commands didnt work and same result just typyng the first word or not working

**Comment by VADemon** [comment]
`.bindmacro f6 "spamservice reset;chatbot en 1;say 'Hello, World'"` works.

Pay attention to single and double quotes. I used single-quotes to enquote `Hello, World` which are encapsulated in the big command enclosed in double-quotes.

For bindmacro, each command is supposed to be a forgehax command. If you want to send a chat message, use `say <msg>` as I did. If you want to target other client-side mods, use `say -l`

Also please dont flood messages like that.

Don't forget to delete your other macros now. I will write the wiki page in an hour.

**Comment by Darko1green1LOrd** [comment]
oh okay , thanks for help

**Comment by VADemon** [comment]
https://github.com/fr1kin/ForgeHax/wiki/Macros

If questions answered you can close.
