### ISSUE TITLE
Crashes before loading.

### ISSUE THREAD

**Issue by iwannadiehard** [fr1kin/ForgeHax#234]
If i try to launch forge 1.16.1 build 32.0.75 with ForgeHax it simply crashes and gives me exit code: 1.

**Comment by fr1kin** [comment]
Yeah its not ready to run outside the IDE yet

**Comment by Ry4n25** [comment]
Any idea when it will be ready to go?

**Comment by fr1kin** [comment]
Yeah it might take a few days. I am writing something I've wanted for long time now and it will take a bit.
