### ISSUE TITLE
New 1.15.2 Forge 31.2.31 throws Method Not found

### ISSUE THREAD

**Issue by big-lip-bob** [fr1kin/ForgeHax#235]
https://hasteb.in/exibuhex.rb
```advancedmacros-10.0.0a.jar
cullparticles-1.0.jar
fastfurnaceminusreplacement-1.0.jar
FastWorkbench-1.15.2-3.1.1.jar
ForgeHax-1.15.2-3.0.0-570c476.jar
lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar
phosphor-forge-mc1.15.2-0.5.2+build.4.jar
Placebo-1.15.2-3.1.0.jar
preview_OptiFine_1.15.2_HD_U_G1_pre30.jar
randompatches-1.15.2-1.22.0.0.jar
```
I doubt Optifine is doing something wrong or i am, grabbed the last succesfull 1.15.2 build from jenkins and this is happening.

**Comment by big-lip-bob** [comment]
Using Forge 31.2.31 for 1.15.2 and i reproduced the same crash with only FH so this is a genuine bug ?

**Comment by fr1kin** [comment]
In newer versions of forge lex changed the arguments of some method. Shouldn't be too difficult to fix as I have already done it for 1.16.1

**Comment by fr1kin** [comment]
Might fix it tomorrow since a lot of people seem to still use 1.15.2

**Comment by fr1kin** [comment]
Fixed in https://github.com/fr1kin/ForgeHax/commit/34d0342f65ad2f0c9e654185c013c1371fb0d87a
