### ISSUE TITLE
How do I install ForgeHax with jenkins?

### ISSUE THREAD

**Issue by circl-lastname** [fr1kin/ForgeHax#237]
Tried downloading but the latest release says to use jenkins. I googled "forgehax jenkins" but found nothing.

**Comment by fr1kin** [comment]
![Screenshot_20200801-132130](https://user-images.githubusercontent.com/12203368/89107937-30121e80-d3fa-11ea-9def-a45336780cfa.png)

Click one of these

**Comment by circl-lastname** [comment]
Oh.

**Comment by AstroOrbis** [comment]
Then that's git and not Jenkins???

**Comment by fr1kin** [comment]
Read carefully

**Comment by AstroOrbis** [comment]
anyone who is following the thread [this](https://jenkins.nhackindustries.com/job/ForgeHax/job/master/lastSuccessfulBuild/) is the link :)
