### ISSUE TITLE
Crash when entering nether

### ISSUE THREAD

**Issue by XorogVEVO** [fr1kin/ForgeHax#238]
Modversion: 1.3.1.0-e41f2da
Forgeversion: 32.0.106

Logs (a few lines before the crash): https://pastebin.com/PrVR2qG7

The crash happens right when loading the nether. It works fine in the overworld but i can't say anything about the end, didn't test it.

**Comment by fr1kin** [comment]
I have this fixed pretty much I just need to fix a few bugs and I'll push my changes later today

**Comment by XorogVEVO** [comment]
Thats nice to hear! I'll be sure to grab it when i see that you updated it. I'll close this issue then.

**Comment by fr1kin** [comment]
My latest commit should fix this issue. However it's still not very usable. I've spent a lot of time refactoring my code to making updating in the future easier, and now I have pretty much completed that. Now I can focus on fixing bugs related to the update from 1.15 to 1.16
