### ISSUE TITLE
Jenkins Download Links Not Working

### ISSUE THREAD

**Issue by maxicode2** [fr1kin/ForgeHax#240]
When clicking links to download build in Jenkins, I get a 404 error.

**Comment by JakeRoggenbuck** [comment]
I tried and it gave a 500 error

**Comment by fr1kin** [comment]
It's working for me right now. Maybe @starcraft66 was doing maintenance.

**Comment by starcraft66** [comment]
I tried downloading all three versions using buttons in the readme and cannot reproduce. Please re-open this issue if the problem persists.

**Comment by maxicode2** [comment]
Yep their working now.
