### ISSUE TITLE
Mod can be detected by server

### ISSUE THREAD

**Issue by Quin32** [fr1kin/ForgeHax#245]
So i've noticed that servers now can detect someone's Mod list, Hence detecting ForgeHax, So i was wondering if there is any way to counter act that by either changing the mods name or just outright removing it from the modlist

Huge fan of your mod btw

**Comment by fr1kin** [comment]
Yes. ForgeHax has a module to hide it. It isn't working right now though (needs to be fixed). However, the jars built by jenkins will not have this module included. If you want it you must build it yourself.

**Comment by UltraBlackLinux** [comment]
Actually the only thing they can detect are the mod's md5s (and the packets). That requires the server to know what md5 is what.

**Comment by fr1kin** [comment]
I am pretty sure forge sends a list of mods the client has installed (unless this changed recently)

**Comment by LoganDark** [comment]
Forge explicitly sends a list of all modids and versions installed on the client. The only way to fix this would be to not be in the mod list, or to patch it somehow to make it skip ForgeHax.

**Comment by fr1kin** [comment]
ForgeHax should hide itself from the modlist (if you enable the spoofer). But this setting is only available if you build forgehax yourself (Jenkins build will not have it). https://github.com/fr1kin/ForgeHax/issues/283
