### ISSUE TITLE
Storage ESP doesnt work

### ISSUE THREAD

**Issue by SP1K33** [fr1kin/ForgeHax#248]
[Screenshot](https://imgur.com/ykSQ05a)
Clean build 1.12.2
Build: https://jenkins.nhackindustries.com/job/ForgeHax/job/master/97/
Build that i found with no issue:  https://jenkins.nhackindustries.com/job/ForgeHax/job/master/95/
I guess we need search commit between versions which irreparably improve storage esp.

**Comment by fr1kin** [comment]
I guess #232 broke something?

**Comment by SP1K33** [comment]
i don't know java, i could try but i don't have IDE right now. debug onRender StorageESPMod, can be anything

**Comment by fr1kin** [comment]
Try https://jenkins.nhackindustries.com/job/ForgeHax/view/change-requests/job/PR-249/

**Comment by SP1K33** [comment]
Works fine, thank you! 👍
