### ISSUE TITLE
Crash when crafting items

### ISSUE THREAD

**Issue by tonksdude** [fr1kin/ForgeHax#257]
Game sometimes crashes when I take an item out of crafting output. Game goes to "Saving World" screen and either freezes or crashes. (I don't remember which it did for each of these crashes, but I know it has done both. It still generated a crash report when I alt-f4'd after it froze though.) I believe I had Aimbot on during all of them, but the crash reports say something about rendering the recipe book so it might not be a problem with ForgeHax at all, rather with OptiFine or just my graphics. However, I haven't experienced crashes like this using OptiFine on the same settings without ForgeHax.

Minecraft: 1.16.2
Forge: 33.0.61
ForgeHax: 3.1.0-00c9818f
OptiFine: HD U G3
OS: Windows 8.1
Java: 1.8.0_251-b08

Crash Reports:
[Crash 1](https://pastebin.com/cKESy7FV)
left-clicked blackstone stairs after crafting manually in a crafting bench
[Crash 2](https://pastebin.com/2kZG7840)
left-clicked fishing rod after crafting with recipe book in crafting bench
[Crash 3](https://pastebin.com/YY6iVAyN)
shift-clicked iron ingots after crafting manually in inventory

**Comment by tonksdude** [comment]
Hopefully that's enough information.

**Comment by fr1kin** [comment]
Doesn't appear to be ForgeHax, most likely just a Forge bug. Try testing with and without ForgeHax and maybe upgrade to 1.16.3
