### ISSUE TITLE
ESP breaks status indicators

### ISSUE THREAD

**Issue by Hydr4gyrum** [fr1kin/ForgeHax#260]
enabling ESP causes the status effect indicators on the top right to become white squares

**Comment by kylerittenhause** [comment]
same issue

**Comment by kylerittenhause** [comment]
![Uploading Screen Shot 2020-10-23 at 9.00.44 PM.png…]()

**Comment by kylerittenhause** [comment]
![Uploading Screen Shot 2020-10-23 at 9.56.28 PM.png…]()

**Comment by fr1kin** [comment]
Fixed
