### ISSUE TITLE
book bot doesnt work

### ISSUE THREAD

**Issue by Peperoni44HD** [fr1kin/ForgeHax#262]
The book bot doesnt work.
It says "Expected 1 Arguments, hot 0", when typing ".bookbot Start" i did the other steps, just as shown in every tutorial
Minecraft Version 1.16.3
Latest Forgehax Version
What does it mean/what did I do wrong?

**Comment by fr1kin** [comment]
Appears to be a bug. The optional page start argument is not marked as optional. Working on a fix right now

**Comment by fr1kin** [comment]
Try the latest build

**Comment by Peperoni44HD** [comment]
I did Download the Latest Version. But now it says "file not found". No other Problems.
I also tried it with multiple txt files, but it didnt work either.
Sry, if I am interrupting you

**Comment by fr1kin** [comment]
There was an issue with the command parser. It was reading past the end of an array, so there would be a null value appended to the end of string settings. About to push a fix for it.

**Comment by fr1kin** [comment]
I tested it myself and BookBot was working perfectly. Reopen if you find any more issues
