### ISSUE TITLE
Chatcommand issue

### ISSUE THREAD

**Issue by NathanWelnicki** [fr1kin/ForgeHax#267]
Hey, so I was messing around with forgehax from the master branch in my ide, and for whatever reason refractoring the package `com.matt.forgehax` to anything else breaks the chat command in game. I have made sure to change the string in the `ForgeHax` main class too the appropriate package. I have also refractor a bunch of other packages to narrow it down and I believe the issue has to do with the `ChatCommandService` class. The main menu console works just fine, and all of the modules do as well, its just the Chatcommand that isn't working. If you have any idea why it would help a ton.

**Comment by fr1kin** [comment]
If you do it correctly there should not be any issues. Make sure to change the package class path string in ForgeHax.java as well
