### ISSUE TITLE
ESP mod considers players as "friendly" instead of "players"

### ISSUE THREAD

**Issue by starcraft66** [fr1kin/ForgeHax#274]
When turning off esp for friendly entities, it also turns it off for players. Changing esp settings for players appears to affect nothing.

Running Minecraft 1.16.4, Forge 35.1.0, ForgeHax 3.2.0-6c1ac617.

**Comment by fr1kin** [comment]
Probably a regression from https://github.com/fr1kin/ForgeHax/commit/ec4a639b70caf5061d1006a1b2fe1033b55002a8

**Comment by starcraft66** [comment]
I should add that there is also a bug related to the classification of hostile mobs vs friendly mobs.

**Comment by fr1kin** [comment]
I'll look into that
