### ISSUE TITLE
can't use badge to download 1.12.2 latest version

### ISSUE THREAD

**Issue by AverageComet250** [fr1kin/ForgeHax#277]
I think the jenkins link is incorrect.

Id recommend moving to github actions and posting build artifacts as releases

**Comment by starcraft66** [comment]
There was a network outage affecting the Jenkins instance. Download badges should be working again.

**Comment by fr1kin** [comment]
If only GitHub actions was more like gitlab ci then maybe I would consider moving it

**Comment by AverageComet250** [comment]
I don't actually see any difference between GitHub actions and gitlab ci except for the fact that one is for GitHub and the other is for gitlab.

**Comment by fr1kin** [comment]
Github limits you on space a lot while gitlab is more lenient. Jenkins is self hosted so I can keep every artifact
