### ISSUE TITLE
Chat commands just dont work in 1.16.4

### ISSUE THREAD

**Issue by TheEpicProgrammer** [fr1kin/ForgeHax#280]

**Comment by TheEpicProgrammer** [comment]
.help does nothing, and other stuff like that

**Comment by fr1kin** [comment]
It's been replaced. Press RShift to open the new CLI

**Comment by TheEpicProgrammer** [comment]
Yes, i do that but none of the commands work

**Comment by fr1kin** [comment]
Are you including the prefix? That is no longer needed

**Comment by KashBeGamin** [comment]
Thanks!

**Comment by S0LiD-ST4T3** [comment]
I do not have a working RShift key. Can it be bound to a new key?

**Comment by fr1kin** [comment]
Yes
