### ISSUE TITLE
Aimbot doesnt work 1.16.4

### ISSUE THREAD

**Issue by dudeman122** [fr1kin/ForgeHax#287]
I don't think that the aimbot doesnt work but I dont know I could be doing something wrong im following the guide and make the settings the way i want but the aimbot doesnt work at all. for bows and melee

**Comment by fr1kin** [comment]
It works for me with latest build. Try enabling targeting on entities? `aimbot target-friendly-mobs true`. Projectile aimbot hasn't been fixed yet

**Comment by dudeman122** [comment]
> 
> 
> It works for me with latest build. Try enabling targeting on entities? `aimbot target-friendly-mobs true`. Projectile aimbot hasn't been fixed yet

I have both friendly and hostile on yet the aimbot doesnt work ill retry with just friendly and get back to you

**Comment by fr1kin** [comment]
I tested and it worked for me.
