### ISSUE TITLE
commands not working in 1.16.4?

### ISSUE THREAD

**Issue by KashBeGamin** [fr1kin/ForgeHax#293]
I'm on 1.16.4 and non of the commands are working. Any help?

**Comment by KashBeGamin** [comment]
![2021-01-22_20 26 03](https://user-images.githubusercontent.com/60108561/105568684-2bb32800-5cf0-11eb-8ca2-35dd28076a70.png)

**Comment by fr1kin** [comment]
#280

**Comment by fr1kin** [comment]
![image](https://user-images.githubusercontent.com/12203368/105568755-6b364000-5d01-11eb-8753-ec828a4ef2e6.png)

Press right shift

**Comment by Rithmatist** [comment]
![unkown command](https://user-images.githubusercontent.com/69980549/114297471-1f4d9880-9ab1-11eb-8497-f7f175e23d2c.JPG)

No command seems to work and i use ForgeHax-1.16.5-3.3.0-40c3a20.jar
