### ISSUE TITLE
cant build 

### ISSUE THREAD

**Issue by Natives3000** [fr1kin/ForgeHax#295]
PS C:\Users\nativ\ForgeHax-1.16> ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by fr1kin** [comment]
What JDK version?

**Comment by fr1kin** [comment]
Oh I just realized you are on windows. You need to run ./gradlew.bat build. Or you can use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by Natives3000** [comment]
I still have the same problem/error I use latest "AdoptOpenJDK" version 
![image](https://user-images.githubusercontent.com/42712457/105912127-4a385c80-602b-11eb-9e0f-c401151c0422.png)

**Comment by fr1kin** [comment]
You need to build with JDK8. If you have docker and docker-compose installed, you may be able to run ./scripts/cibuild (in linux compatibility mode) to build with proper tools

**Comment by Natives3000** [comment]
i'm on windows 10 and isnt there a way to make it work with openjdk? (sorry for late response)

**Comment by fr1kin** [comment]
The project is built with OpenJDK8. You can see what version of java you are running with `java -version`. It should be Java 1.8.x. If you are running latest JDK you need to install an earlier one and change JAVA_HOME to point to that JDK.

**Comment by Natives3000** [comment]
worked but would it work in the future with openjdk 15?

**Comment by fr1kin** [comment]
There is a lombok extension that uses javac classes that are subject to heavy changes every java update. Next update will probably be the next java LTS which is 11 or 17
