### ISSUE TITLE
BookBot doesn't sign after the first book

### ISSUE THREAD

**Issue by Horse-5-333** [fr1kin/ForgeHax#298]
BookBot won't sign multiple books. I made sure `sign=true` and set the sleep delay quite high to ensure it wasn't any kind of lag. Still only the first book got signed.

**Comment by fr1kin** [comment]
1.16.4?

**Comment by Horse-5-333** [comment]
Yes

**Comment by fr1kin** [comment]
Just verified. Will investigate

**Comment by fr1kin** [comment]
Should be fixed
