### ISSUE TITLE
Add Wiki pages?

### ISSUE THREAD

**Issue by VADemon** [fr1kin/ForgeHax#30]
Hi, looks like an awesome and exhaustive mod, props for that.

I'm ready to create wiki pages about features based on current documentation in chat. But I need you to enable wiki for that, it's unavailable to me. Deal?

**Comment by fr1kin** [comment]
sorry about the wait, was waiting on the 1.13 update before continuing the project. i'll add the wik,i if you still care.

**Comment by VADemon** [comment]
Wiki is available as a tab, but I have no rights to edit/add anything on it

**Comment by fr1kin** [comment]
Alright, done.
