### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SKITLSE** [fr1kin/ForgeHax#300]
[ForgeHaxASM]: Application data folder does not exist and cannot be created.
 [main/ERROR] [ForgeHaxAsmStackTrace]: com.matt.forgehax.asm.utils.remapping.MCPMappingLoader$CantLoadMCPMappingException: Application data folder does not exist and cannot be created.
Help plz

**Comment by fr1kin** [comment]
Probably related to #104

**Comment by SKITLSE** [comment]
I use linux

**Comment by fr1kin** [comment]
As do I. For some reason ForgeHax isn't able to create or read `~/.cache/MCPMappingViewer`

**Comment by SKITLSE** [comment]
I can to send full log i use the phone and aplication MCinaBox
https://pastebin.com/mQtHWGbR log

**Comment by fr1kin** [comment]
MCinaBox is the problem.
