### ISSUE TITLE
Crash on linux device

### ISSUE THREAD

**Issue by SKITLSE** [fr1kin/ForgeHax#301]
[ForgeHaxASM]: Application data folder does not exist and cannot be created.
[main/ERROR] [ForgeHaxAsmStackTrace]: com.matt.forgehax.asm.utils.remapping.MCPMappingLoader$CantLoadMCPMappingException: Application data folder does not exist and cannot be created.
Help plz i use a linux device

**Comment by fr1kin** [comment]
Don't open another issue. I will reply to the previous one.
