### ISSUE TITLE
Forgehax doesn't work 1.16.4

### ISSUE THREAD

**Issue by faustojc** [fr1kin/ForgeHax#302]
After I download and install the ForgeHax jar file into .minecraft/mods/ folder. starting Minecraft, checking in the Mods to see if the ForgeHax was loaded, creating new world and loaded. When I press the right-shift key and typed .help, it says "Unknown command". There is NO dropdown suggestion I tried every command still "Unknown command". I check the forgehax/config folder. It's empty. Need help :(

Forgehax version: ForgeHax-1.16.4-3.2.0-d5293272

**Comment by fr1kin** [comment]
You don't need to append a period anyone

**Comment by faustojc** [comment]
I'll check again

**Comment by faustojc** [comment]
welp it works I've been following the FAQ on how to use the commands, thanks for the help

**Comment by fr1kin** [comment]
Yeah sorry it's not kept updated

**Comment by faustojc** [comment]
It's ok man
