### ISSUE TITLE
crashing while clicking a button

### ISSUE THREAD

**Issue by Natives3000** [fr1kin/ForgeHax#303]
by example when I click the option or play survival button it crash me with error "The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error"

i use openjdk 8

here's the crash report
[crash-2021-01-31_11.59.56-client.txt](https://github.com/fr1kin/ForgeHax/files/5899570/crash-2021-01-31_11.59.56-client.txt)

**Comment by fr1kin** [comment]
I think this happens if you have a mouse with more than 3 mouse buttons

**Comment by Natives3000** [comment]
im on laptop and so its a touch pad and only have right and left button, i've also touched at the controls key of forgehaxx for open the ui or the enabled mods and so I think i **might** have put one of those button to left click or right click, i've already tryed to delete forgehax mod and its folder of .minecraft and reinstalling it but dont change anything
