### ISSUE TITLE
Regarding to commands and nofall

### ISSUE THREAD

**Issue by xjunsu** [fr1kin/ForgeHax#304]
I noticed some of the commands on the wiki are quite outdated (specifically markers since the command it now uses is block instead of options) and been trying to figure out the commands for limiting block distance for markers. Tying --help -? or any of the suggestions in the list does not show a list of commands for a specific mod. --bounds <min>-<max> just dosent seem to work.

 Also I read nofall would be fixed on a another issue and was wondering if the fix would also be implemented since we're still dying from fall damage.

**Comment by fr1kin** [comment]
Yeah sorry I don't maintain the wiki. I haven't fixed nofall yet. I guess I'll do that today since its requested so much.

**Comment by xjunsu** [comment]
> Yeah sorry I don't maintain the wiki. I haven't fixed nofall yet. I guess I'll do that today since its requested so much.

Really appreciate the response! Just in case, the version im using is 1.16.4. By any chance do you happen to know the new commands to limit marking block distance or has that option been removed?

**Comment by fr1kin** [comment]
Was this a feature in markers or storageesp? It certainly doesn't exist in 1.16.4 but I don't remember it existing in previous versions either.

**Comment by xjunsu** [comment]
> Was this a feature in markers or storageesp? It certainly doesn't exist in 1.16.4 but I don't remember it existing in previous versions either.

https://github.com/fr1kin/ForgeHax/wiki/Markers 

Under Markers. 
"To limit distance where blocks will be marked: --bounds <min>-<max> e.g. --bounds 16-500"

Reason why I'd like to use this is because certain blocks that are quite abundance like coal and iron are hard to see when there are 100s of marking behind meshing together.

**Comment by fr1kin** [comment]
Oh I think that was y axis only though. Used to find tunnels at the top and bottom of the nether. XRay allows you to add blocks now so you can use that instead if you find markers too distracting.

**Comment by xjunsu** [comment]
> Oh I think that was y axis only though. Used to find tunnels at the top and bottom of the nether. XRay allows you to add blocks now so you can use that instead if you find markers too distracting.

ahh I did give xray a try before but never really figured it out how to get it to work. I just assumed its because of the forge modpack im using makes xray not work but I havent tried using it on a normal forge non modpack to see if thats really the case.
