### ISSUE TITLE
Baritone Compatibility Doesn't Work [1.16.4]

### ISSUE THREAD

**Issue by mrcackalacky** [fr1kin/ForgeHax#305]
Everytime I try to use the baritone compatibility command it says unknown command.

**Comment by fr1kin** [comment]
It's a shitty 'compatibility' mod I made so I could at minimum autoeat while afk mining.

**Comment by mrcackalacky** [comment]
Ah ok I gotcha. Yeah well I think my issue stems a little deeper. At least you can actually use the mod. Trying to get baritone to actually do what its programmed to do is giving me issues right now.
