### ISSUE TITLE
Aimbot not working 1.16.4

### ISSUE THREAD

**Issue by Csquaredaap** [fr1kin/ForgeHax#307]
I have been trying to get aimbot to work but no matter what i do it refuses to attack or do anything. I have checked every single setting and nothing is working. how do i turn it on because using the enable option in the gui obviously doesnt work

**Comment by fr1kin** [comment]
It is working for me when using the latest version.

**Comment by Csquaredaap** [comment]
how did you set it up?

**Comment by fr1kin** [comment]
`aimbot target-hostile-mobs true`
`aimbot target-players true`
`aimbot enable`

**Comment by Csquaredaap** [comment]
thank you i will try again

**Comment by Csquaredaap** [comment]
Nothing happens when those settings are enabled..... is it supposed to automatically attack?

**Comment by fr1kin** [comment]
Yes. Maybe `aimbot auto-attack true`? Somebody else had this issue. But I am not sure why it would be happening other than misconfiguration or some mod conflicting with it.

**Comment by Csquaredaap** [comment]
that has been on

**Comment by Csquaredaap** [comment]
the only mods i hav are baritone, optifine, and terraforge

**Comment by fr1kin** [comment]
Try removing baritone.

**Comment by Csquaredaap** [comment]
ok

**Comment by Csquaredaap** [comment]
still not working

**Comment by fr1kin** [comment]
Okay I figured it out. You need to disable the projectile aimbot (which isnt even implemented) `aimbot proj-aimbot false`

**Comment by Csquaredaap** [comment]
ok thanks ill try that
