### ISSUE TITLE
Crashes during initialization of Minecraft forge 

### ISSUE THREAD

**Issue by Robertma27** [fr1kin/ForgeHax#308]
The latest version of forge is installed (1.16.4 - 35.1.37) and the latest version of forgehax (ForgeHax-1.16.5-3.3.0-6431a082.jar) is in the .minecraft/mods directory, there are no other files/mods in this directory except forgehax. 
There are no other non-vanilla installations either apart from the latest version of forge. 
When forge is opened from the Minecraft launcher, forge runs and gets stuck on "waiting to complete scan" and then crashes, the Minecraft launcher giving the following message: 
 
"The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: dev/fiki/forgehax/api/event/Event
Exit Code: -1"

Un-installing then re-installing forge had no effect

Thank you for any information on this issue

**Comment by fr1kin** [comment]
Wouldn't latest be 1.16.5?

**Comment by Robertma27** [comment]
Yes you are absolutely right! I went back and checked and the version when you open http://files.minecraftforge.net/ is not the latest version, but the 1.16.4 version even though it says "download latest version"
you have to look at the left of the website that has the version list, and select the top-most version (which is 1.16.5)

sorry for the confusion

Thank you it loads correctly now !
