### ISSUE TITLE
Enhance AntiAFK against AntiAFK+

### ISSUE THREAD

**Issue by VADemon** [fr1kin/ForgeHax#31]
[AntiAFK+ Spigot Plugin](https://www.spigotmc.org/resources/antiafk-detect-every-afk-form-recoded.21208/)

This plugins seems to ONLY check player's facing direction
`v.equals(p.getLocation().getDirection())`
where `v` is the old direction.

**Work-around 1:** Change player's view by a few decimal places, but it must remain changed until the next Anti-AFK check for plugin to pick it up.
**Work-around 2:** Without permanently changing player position/facing direction: The Plugin removes AFK state if the player's facing direction changes `@EventHandler onMove`. 

1. Change facing direction
2. Move (plugin removes AFK state)
3. Change back to direction from 1)
4. Move back to position from 2)

**Comment by fr1kin** [comment]
i'll look into making the anti-afk more robust for the 1.13 update

**Comment by fr1kin** [comment]
Added
https://github.com/fr1kin/ForgeHax/commit/28082f3c877c2abe31a15a9075b63804f629bacd
