### ISSUE TITLE
crash when launching

### ISSUE THREAD

**Issue by HW12345** [fr1kin/ForgeHax#318]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: dev/fiki/forgehax/api/event/Event
Exit Code: -1
btw I use with journeymap and use forge 35.1.37

**Comment by fr1kin** [comment]
Possibly https://github.com/fr1kin/ForgeHax/issues/308?

**Comment by HW12345** [comment]
> Possibly #308?

i don't know but i run the latest on 1.16.4

**Comment by fr1kin** [comment]
You need to run 1.16.5, or the last 1.16.4 version
