### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by HackD8** [fr1kin/ForgeHax#323]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: dev/fiki/forgehax/api/event/Event
error code: 255

I have 1.16.4(forge) and some other mods installed

**Comment by HackD8** [comment]
I think the problem is that I need the 1.16.4 ForgeHax version not the 1.16.5 one...
if this was the case where can I find the 1.16.4 version?

**Comment by fr1kin** [comment]
#308
