### ISSUE TITLE
ForgeHax Versions BROKEN

### ISSUE THREAD

**Issue by PussySpread** [fr1kin/ForgeHax#324]
Hi everyone
There is too many bugs here ; 
In the ForgeHax Versions 1.15.2 There is no Xray Mod. There is not a Key to open the Gui like in the 1.12 versions.  
In the 1.12 versions, Only the opacity options of the xray mod is enabled the other are broke. 
On the website we can't download the 1.16 versions anymore

**Comment by fr1kin** [comment]
1.15 and 1.12 are no longer actively developed by me. Right now I am working on migrating from jenkins to github actions. 1.16 is downloadable at https://github.com/fr1kin/ForgeHax/actions and I will be fixing the links up later today

**Comment by simulatorwinner** [comment]
can u make a 1.15.2 version then ?

**Comment by simulatorwinner** [comment]
or make the old one public ?

**Comment by simulatorwinner** [comment]
can u use something like via-forge/via-version/via-rewind to use forge hax on 1.15.2 ?
