### ISSUE TITLE
Jenkins download links broken

### ISSUE THREAD

**Issue by fr1kin** [fr1kin/ForgeHax#325]
Currently migrating from jenkins to actions because tristan does not want to manage a jenkins instance anymore since it seems to only cause issues. Right now artifacts can be downloaded from https://github.com/fr1kin/ForgeHax/actions but I will make everything more elegant later.

**Comment by PussySpread** [comment]
whats jenkin

**Comment by WoodenSquid** [comment]
how do we use the action to get the jar?

**Comment by UltimateBoi** [comment]
> whats jenkin

bruh

**Comment by UltimateBoi** [comment]
git actions is actually an easier way of doing stuff you know

**Comment by UltimateBoi** [comment]
also can you make a gui for the 1.16 version?

**Comment by usoonerd** [comment]
How do i download it, i can only come to the actions tab but there is nothing to click that downloads the artifact

**Comment by fr1kin** [comment]
Good catch. I guess I should actually get around to finishing migrating now.

**Comment by fr1kin** [comment]
Should be fixed (for 1.16 for now) You can now download from the release section.
