### ISSUE TITLE
Commands are not working on 1.16.5

### ISSUE THREAD

**Issue by Rithmatist** [fr1kin/ForgeHax#327]
I keep getting this:

![unkown command](https://user-images.githubusercontent.com/69980549/114297572-9aaf4a00-9ab1-11eb-855d-3665fb2f2779.JPG)

i use ForgeHax-1.16.5-3.3.0-40c3a20.jar

**Comment by fr1kin** [comment]
Are you prepending a period? You don't do that anymore

**Comment by Rithmatist** [comment]
I see, the dot isn't required anymore.

**Comment by navarayuk** [comment]
This does not work with or without, I tried fly enable 1 and many others and no command works and help tells me to use find that's only commands that seem to work.

**Comment by playstation452** [comment]
bro forgot
