### ISSUE TITLE
unable to find 1.16.3 download

### ISSUE THREAD

**Issue by jordann1** [fr1kin/ForgeHax#331]
ive been trying to find this for 5 hours

googled
checked reddit
downloaded intellij idea specifically for this and it still gave me 1.16.5

please help thanks

**Comment by fr1kin** [comment]
clone the project with git then in the project root direction type `git checkout cbf365e3ceaf18f52ca567f51434a37b9a8a7388` and then run `./gradlew build`

**Comment by jordann1** [comment]
thank you that worked
