### ISSUE TITLE
Bookbot

### ISSUE THREAD

**Issue by sspenceyy** [fr1kin/ForgeHax#342]
When I turn on bookbot in forgehax nothing happens. None of the commands work for me. Correct me if I am wrong but it should go ".bookbot file example.txt" into the normal chat. When I do that and hold out a book and quill nothing happens.  If anyone knows how to fix this please let me know.

**Comment by fr1kin** [comment]
Minecraft version?

**Comment by sspenceyy** [comment]
> Minecraft version?

1.16.5

**Comment by fr1kin** [comment]
It should be working. Last bug I fixed was #298

**Comment by sspenceyy** [comment]
> It should be working. Last bug I fixed was #298

I don't know why it doesnt work for me though. I went through the wiki, I put the text file into .minecraft\forgehax but the commands just dont work for me. Heres a screenshot of the problem for me.
![bookbot](https://user-images.githubusercontent.com/84258198/118384847-5131ad80-b5cf-11eb-9731-ed234fd01cb2.png)

**Comment by fr1kin** [comment]
https://github.com/fr1kin/ForgeHax/wiki/FAQ#in-forgehax-3x-versions

**Comment by sspenceyy** [comment]
> https://github.com/fr1kin/ForgeHax/wiki/FAQ#in-forgehax-3x-versions

When I do ".bookbot enabled 1" In chat nothing happens and when I put it in the GUI GUI part it says unknown command.

**Comment by sspenceyy** [comment]
When I do ".bookbot enabled 1" In chat/gui and then do the .bookbot file randombook.txt still nothing happens***

**Comment by fr1kin** [comment]
Try reading the FAQ very carefully

**Comment by sspenceyy** [comment]
> Try reading the FAQ very carefully

I fixed it. I just downgraded to 1.12.2 and everything works fine. Thanks for your help though.
