### ISSUE TITLE
Forgehax crashing when opening world

### ISSUE THREAD

**Issue by FatRainbow** [fr1kin/ForgeHax#344]
Every time I join a world it loads but then it says saving world and crashes. Is there any way to fix this?

**Comment by fr1kin** [comment]
post crash report

**Comment by FatRainbow** [comment]
[crash-2021-05-22_23.36.29-client.txt](https://github.com/fr1kin/ForgeHax/files/6527488/crash-2021-05-22_23.36.29-client.txt)

I don't know what it means

**Comment by fr1kin** [comment]
It's an issue with Optifine G8. I actually have it fixed give me a minute to push my change.

**Comment by fr1kin** [comment]
Okay should be fixed in 0392274c6f8a569fc5a19c59fd36785b7e312606

**Comment by FatRainbow** [comment]
Ok, thank you
