### ISSUE TITLE
Markers Commands

### ISSUE THREAD

**Issue by EvilEpicPanda** [fr1kin/ForgeHax#356]
I've been trying to use markers, but it seems the commands have been updated.

The wiki calls for:
.markers options ... - blocks options.

       add <type> - adds block <type>. Must be a valid (namespaced) type

       add <id> --id - adds block referred to by <id>

       add <regex> --regex - adds all blocks that are matched by this regex (good example: Dirt)

       remove <type> - removes given type from markers

       remove <type> [--regex / --id] [--meta <metadata id>] [--bounds "<min>-<max>"]

`markers options` is no longer a command
       
I'm trying to add a block using regex. From `markers blocks add diamond --regex` I get `color expected 3 or 4 arguments, got 1`

**Comment by EvilEpicPanda** [comment]
I also tried doing `markers blocks add diamond --red 0 --green 0 --blue 0 --alpha 255 --regex` and got `For input string: "--red"`

**Comment by fr1kin** [comment]
1.16.5?

**Comment by EvilEpicPanda** [comment]
> 1.16.5?

Yep

**Comment by fr1kin** [comment]
Try `markers blocks add diamond 0 0 0 255` or `markers blocks add diamond black` A lot of the wiki is written for 1.12.2 and I have made major changes since then

**Comment by EvilEpicPanda** [comment]
`block argument is invalid or missing` did the regex argument change as well?

`markers blocks add diamond_ore 0 0 0 255` works, but only looks for minecraft:diamond_ore and not other types. This mod pack includes diamond in different types of blocks.

**Comment by fr1kin** [comment]
Maybe try `markers blocks bulkadd diamond_ore* black`. I forgot what exactly I named the bulk add command but it's something like that

**Comment by EvilEpicPanda** [comment]
That worked! although the "*" was messing it up.

`markers blocks bulk-add diamond_ore black` worked perfectly
![hxhkLXz](https://user-images.githubusercontent.com/20939715/128386134-8a094ddb-d7ff-406d-979e-e4ef89b45a2f.png)
![UGHBiyd](https://user-images.githubusercontent.com/20939715/128386154-0905ad68-8d09-4254-b281-d3a71e101979.png)

**Comment by EvilEpicPanda** [comment]
If I go and look in the config, I can see a list of the added blocks. I tried changing the file and then toggling markers off and back on again, but it doesn't seem like that worked and when I refreshed the file, the blocks were still there.

**Comment by fr1kin** [comment]
You would have to close the game and make your changes then for them to persist. The reason why its adding a bunch of random blocks is because I do `contains(match)` instead of a regex-style match. Ideally, I would implement something that would accept wildcards so you could do something like `diamond_*_ore` instead of a regex-style expression `^diamond_.*_ore$`.

**Comment by EvilEpicPanda** [comment]
Wildcards would be nice, especially on the remove command to make it easier to switch between looking for different blocks.

**Comment by fr1kin** [comment]
You should be able to do `markers blocks madd minecraft:diamond_*_ore` now.

Here are some examples of the wildcard format
`minecraft:*shulker_box` gets every shulkerbox in vanilla minecraft
`*:diamond_*ore` gets blocks named like diamond_ore, diamond_foo_ore, diamond_foo_bar_ore
`*diamond*` gets any block named diamond
`*` gets every single block in the game

**Comment by EvilEpicPanda** [comment]
Thanks for the fast fix! Awesome.

Do I need to compile the jar myself or is there an auto update function?

**Comment by fr1kin** [comment]
The github release jar should be updated

**Comment by EvilEpicPanda** [comment]
I'm not seeing it updated under releases, but I just compiled it myself, so all good. Will test now.

**Comment by EvilEpicPanda** [comment]
I tried `markers blocks bulk-add diamond_*_ore` and got:
`Found no blocks matching diamonnd_*_ore
Did you mean "minecraft:diamond_*_ore?"`
