### ISSUE TITLE
Cannot Attack

### ISSUE THREAD

**Issue by Crni39** [fr1kin/ForgeHax#365]
I cannot attack anything, after i first time turned aimbot, 1.16.5

**Comment by fr1kin** [comment]
Is projectile aimbot enabled? That is usually the cause.

**Comment by fr1kin** [comment]
Type `aimbot proj-aimbot 0` to disable it.

**Comment by Crni39** [comment]
nope, not working, when is that disabled aim cannot attack at all

**Comment by fr1kin** [comment]
Probably related to #197

**Comment by Crni39** [comment]
@fr1kin now when i removed left click from aim bot, i can normal attack and aim bot cannot, please fix this.
