### ISSUE TITLE
Add auto duper on 1.12.2 forgehax

### ISSUE THREAD

**Issue by Unknitcandy2585** [fr1kin/ForgeHax#366]
Pls add features on forgehax 1.12.2 and 1.16.5

-duper
Description:
Like the donkey chest dupe on creepy salhack
-operator commands
Description:
Behold my power!
-gamemode changer (it works even if your on admin)
Description:
It has never been usefull as before
-item multiplier (the brother of duper)
Description:
If you hold a item.
It will start duping it.

**Comment by Unknitcandy2585** [comment]
I mean (it works even if your not admin)

**Comment by fr1kin** [comment]
I don't maintain the 1.12.2 version anymore.

**Comment by Unknitcandy2585** [comment]
Okay.

**Comment by Unknitcandy2585** [comment]
Im a little bit sad that your not updating forgehax 1.12.2 anymore :(
