### ISSUE TITLE
1.15 cannot be build

### ISSUE THREAD

**Issue by LoafedBun** [fr1kin/ForgeHax#373]
I can build 1.16 version but not 1.15 because the cmd say there is a problem with build.gradlew on line 5

**Comment by fr1kin** [comment]
and that error is...?

**Comment by LoafedBun** [comment]
* What went wrong:
A problem occurred evaluating root project 'ForgeHax'.
> A problem occurred starting process 'command 'git''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 

when I put git into environment variable 

> Configure project :
fatal: not a git repository (or any of the parent directories): .git

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\lolyi\Downloads\ForgeHax-1.15\build.gradle' line: 5

* What went wrong:
A problem occurred evaluating root project 'ForgeHax'.
> Process 'command 'git'' finished with non-zero exit value 128

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by fr1kin** [comment]
You need to clone the repository with git... don't download the project as a zip

**Comment by LoafedBun** [comment]
cloning doesn't clone 1.15 so I download and extract the 1.15 zip

**Comment by fr1kin** [comment]
`git clone <url> -b 1.15`

**Comment by LoafedBun** [comment]
> Configure project :
New Dep: net.minecraftforge:forge:1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1

FAILURE: Build failed with an exception.

* What went wrong:
Task 'SETUPDECOMPWORKSPACE' not found in root project 'ForgeHax'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

**Comment by fr1kin** [comment]
you dont need to run setupDecompWorkspace

**Comment by LoafedBun** [comment]
> Task :compileApiJava FAILED

FAILURE: Build failed with an exception.

**Comment by LoafedBun** [comment]
* What went wrong:
Execution failed for task ':compileApiJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find net.minecraftforge:forge:1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.pom
       - https://repo.maven.apache.org/maven2/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.jar
       - https://oss.sonatype.org/content/groups/public/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.pom
       - https://oss.sonatype.org/content/groups/public/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.jar
       - https://maven.minecraftforge.net/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.pom
       - https://maven.minecraftforge.net/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.jar
       - file:/C:/Users/lolyi/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.pom
       - file:/C:/Users/lolyi/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.jar
       - https://libraries.minecraft.net/net/minecraftforge/forge/1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1/forge-1.15.2-31.2.47_mapped_snapshot_20200126-1.15.1.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
1 actionable task: 1 executed

**Comment by fr1kin** [comment]
you need jdk8 or forge maven is griefed (again)

**Comment by LoafedBun** [comment]
I have jdk 8
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

**Comment by fr1kin** [comment]
I just cloned the branch and ran `./gradlew build` successfully. No clue where you are having problems.

**Comment by fr1kin** [comment]
Anyway, I have assisted you as much as I can. You're on your own now.

**Comment by LoafedBun** [comment]
I forget to delete the file that download as zip and when I deleted it it build successfully thanks bro!
