### ISSUE TITLE
how do i change pic in the waifuESP mod?

### ISSUE THREAD

**Issue by zombiejohn22** [fr1kin/ForgeHax#376]
i want my friends to look like Shrek, and I'm not Shure how to change this. i know its not a bug, but idk where to post stuff like this. sry ;-;

**Comment by fr1kin** [comment]
You have to change [this](https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/mods/WaifuESP.java#L46) line

**Comment by zombiejohn22** [comment]
ty
