### ISSUE TITLE
adding x-ray blocks 1.12.2

### ISSUE THREAD

**Issue by ifallensyko** [fr1kin/ForgeHax#389]
cant add blocks in 1.12.2
tried ingame

- **.xray blocks**
- **.xray add blocks**
- **.xray add** 

comes back with ; unknown command 

tried to edit the xray configs but there are only 3

- **xray enabled - true/false**
- **opacity - #** 
- **xray - for the keybind**

dont know where to add a list

**Comment by fr1kin** [comment]
I never added that functionality to 1.12 and probably never will

**Comment by ifallensyko** [comment]
aight, which of the config files do i edit to manually enter blocks for x-ray
or do you mean you never added xray to 1.12.2

**Comment by fr1kin** [comment]
Latter

**Comment by ifallensyko** [comment]
aight, appreciate the response and your work
ps; if you can bother with 1.16.5 gui, its a pain in the ass but really convenient, if you got spare time ;p
