### ISSUE TITLE
could you please help me with this 

### ISSUE THREAD

**Issue by samuwunuzels** [fr1kin/ForgeHax#391]
![Uploading 2021-11-13_17.23.28.png…]()

**Comment by samuwunuzels** [comment]
![2021-11-13_17 23 28](https://user-images.githubusercontent.com/92439260/141608730-f00336b4-f4f3-4210-a949-ed6a02535566.png)


im not sure whats happening

**Comment by fr1kin** [comment]
I need to see latest.log and possibly debug.log

**Comment by samuwunuzels** [comment]
ok sure how do i check that

**Comment by samuwunuzels** [comment]
and im also using optifine and future client

**Comment by samuwunuzels** [comment]
does that make a diffrence

**Comment by fr1kin** [comment]
No that should not be an issue. Logs will be in `.minecraft/logs/latest.log`

**Comment by samuwunuzels** [comment]
[latest.log](https://github.com/fr1kin/ForgeHax/files/7532890/latest.log)

**Comment by fr1kin** [comment]
You need to find the correct log when you had forgehax installed or add it again and retry. ForgeHax is missing from this log

**Comment by samuwunuzels** [comment]
ok

**Comment by samuwunuzels** [comment]
[2021-11-13-7.log](https://github.com/fr1kin/ForgeHax/files/7532926/2021-11-13-7.log)

**Comment by fr1kin** [comment]
You are using ForgeHax 2.8.0 which I dont believe had bookbot
