### ISSUE TITLE
Forgehax crashes upon startup in 1.16.5

### ISSUE THREAD

**Issue by Serial-Comma** [fr1kin/ForgeHax#392]
Debug.log: https://gist.github.com/Serial-Comma/de16e43b417a099f1325d7883be118c4
Crash report: https://gist.github.com/Serial-Comma/479a21561cabca5aff11db654edd66e4

Hi, after launching minecraft, I get the error:
`Forgehax (forgehax) encountered an error during the sided_setup event phase  `
`java.lang.Error: ForgeHax failed to intalize`

All other mods load successfully, what's wrong?

**Comment by fr1kin** [comment]
> Exception message: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.net.URL java.net.URLConnection.url accessible: module java.base does not "opens java.net" to unnamed module @628e2664

Strange...

**Comment by Serial-Comma** [comment]
too many mods for forgehax to handle?

**Comment by fr1kin** [comment]
It may have to do with your java version. Try using java 11 or java 8

**Comment by Serial-Comma** [comment]
can verify, tried openjdk 11 and forgehax works flawlessly. Thank you.
