### ISSUE TITLE
ForgeHax 3.3.1-eca8932 for Minecraft 1.16.5 | Failed to load in FML [MajorBug]

### ISSUE THREAD

**Issue by JamTheAdventurer** [fr1kin/ForgeHax#395]
Hello, this is JamStudios but it's my new account, we have discovered a problem while loading your mod in Forge Mod Loader (FML) and it would crash and say something that it failed to load during Early Forge Mod Loading.

- Tested Version: [ForgeHax 3.3.1-eca8932 for Minecraft 1.16.5 ](https://github.com/fr1kin/ForgeHax/releases/tag/1.16.5-3.3.1)
- Tested Date:  11/22/2021 | Monday
- Minecraft Version: 1.16.5 - Forge
- Mod Loader: [Forge - 36.2.9](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html)
- Java Version: [JDK SE 17](https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html)
- ModPack: [Dynamic Client](https://github.com/JamStudios/DynamicClient)
- CrashLogs: [Pastebin](https://pastebin.com/bR74htF7)
Mods Included:
- Appleskin made by squeek502
- Xray Mod made by ATE48, ThaEin
- Xray Mod (Advanced) made by Error_MiKeY
- Xaero's Minimap made by xaero96
- Xaeros's World Map made by xaero96
- Inventory HUD+ made by dmitrylovin
- Automining made by waechter_von_atlantis
- World Edit made by sk89q, wizjany_, me4502, octylFractal
- Auto ToolSwap made by MelanX
- Neat made by Vazkii
- Just Enough Items made by mezz, CFGrafanaStats
- AI Improvements made by QueenOfMissiles, bl4ckscor3, dmodoomsirius, builtbrokenbot
- Discord Intigration made by ErdbeerbaerLP
- Auto Sprint made by Lothrazar, NillerMedDild
- Game Menu Mod Option made by morimori0317
- Tbsc Click made by Tbsc_
- Attributes Fix made by DarkhaxDev
- Inventory Tweaks (Renewed) made by David1544, yuitakaa
- Precise Block Placing made by NinjaPhenix, tterrag1098
- Classic Combat made by WildBamaBoy
- Crafting Tweaks made by BlayTheNinth
- Shulker Tooltips made by ZephaniahNoah
- AutoFish made by NorthWestWindNWW and N0rthwestW1nd
- Cloth Config API for Forge [For Autofish] made by shedaniel and linkieisbetterthank9
- Jade [Waila] made by Snownee_
- Inventory Hotswap made by Areuthreateningme
- Mine Menu made by Girafi and dmillerw
- Tips made by DarkhaxDev
- ServerTabInfo made by black_dog20
- TrashSlot made by BlayTheNinth
- Notes made by Chaosyr
- SttepUp made by NotTooManyItems
- InventoryTweaks made by David1544
- Better Advancements made by way2muchnoise
- Ding made by ohaiiChun
- Entity Culling made by tr9zw
- Betty's Coordinates+
- Swing Through Grass made by exidex
- Quick Search made by nero_surfing
- ReAuth made by TechnicianLP
- Spawner Fix made by MacTso & lupicus
- AutoTotem made by Serilum
- ArmorHotswap made by Areuthreateningme
- Baritone made by cabaletta
- Custom Crosshair made by Sparkless101
- EditSign made by RakSrinaNa
- BetterZoom mrscauthd
- InvMove made by PieKing1215
- Emojiful made by Buuz135, The_CodedOne, hrznstudio
- Clumps made Jaredlll08
- RandomPatches made by TheRandomLabs
- Enchantment Description made by DarkhaxDev
- Litematica made by masady
- Malilib made by masady
- SmoothBoot made by UltimateBoomer
- JumpOverFences made by Kreezxil
- Ferritecore made by malte0811
- Distant Horizons made by James_Seibel, cola98765 and leonardoamato
- FastFurnace made by Shadows_of_Fire
- FastWorkbench made by Shadows_of_Fire
- ToastControl made by Shadows_of_Fire
- Placebo made by Shadows_of_Fire
- ForgeHax made by fr1kin, babbaj, VADemon and LoganDark
- Not Enough Crashes made by NatanFudge
- Voice Chat made by henkelmax, Strideyyy, BreadLoaf___
- Chunk Animator made by Lumien231 and HarleyOConnor
- Cosmetic Armor Reworked made by LainMI
- Fast Leaf Decay made by olafskiii
- EmoteCraft made by KosmX New
- UTeamCore made by HyCraftHD and Mr_Troble New
- MusicPlayer made by HyCraftHD New
- FarSight made by someaddon New
- Emojiful made by Buuz135, The_CodedOne and hrznstudio New
- Blur made by tterrag1098 New
- Not Enough Animations made by tr9zw New
- TRansliterationLib made by tr9zw New
- DefaultSettings made by PT400C and Compaszer New
- ChatHeads made by dzwdz and Fourmisain New
- Catalogue made by MrCrayfish New

**Comment by fr1kin** [comment]
Looks like #392
