### ISSUE TITLE
Issue on MC Launch

### ISSUE THREAD

**Issue by CDAGaming** [fr1kin/ForgeHax#4]
![2017-06-25](https://user-images.githubusercontent.com/16328918/27523056-96b7e2a2-59df-11e7-8ccb-1357c383f394.png)

**Comment by ili-codes** [comment]
look in your mods folder, there should be 2 forgehax's. delete one
done

**Comment by CDAGaming** [comment]
Nope only one of its jar file is in there, I'll send screenshot later

**Comment by ili-codes** [comment]
yes please

**Comment by fr1kin** [comment]
If you are running from the IDE, remove the forgehax jar from the run/mods directory. You might have accidentally added it to the libs/ folder as well.
