### ISSUE TITLE
Old Minecraft

### ISSUE THREAD

**Issue by NullHF** [fr1kin/ForgeHax#40]
Hello is possible you make a 1.7.10 version please ? 
Sorry for my bad english

**Comment by fr1kin** [comment]
I have no current plans to support older versions of Minecraft at the moment. The differences between versions are too big to easily port.

**Comment by NullHF** [comment]
Too sad
Still a lot of players and server uses 1.7.10
You would be happy
Anyway, some modules in 1.7.10 would be possible?
