### ISSUE TITLE
How to remove/hide the module toggle messages from chat?

### ISSUE THREAD

**Issue by gonzuwux** [fr1kin/ForgeHax#406]
Title and yeah would really need this. 1.12.2 forgehax

**Comment by gonzuwux** [comment]
I didn't know how to add a label, but yeah this is a question not a issue.

**Comment by fr1kin** [comment]
I don't believe you can.

**Comment by gonzuwux** [comment]
Ah crap.
What if I somehow removed the code where it outputs enabled/disabled on chat?

**Comment by fr1kin** [comment]
Yeah should be simple
