### ISSUE TITLE
is there a way to change the prefix? 

### ISSUE THREAD

**Issue by AustinMemeLord** [fr1kin/ForgeHax#41]
is there a way to change the "." prefix to something else?

**Comment by fr1kin** [comment]
Yes. In the Input Menu or chat type `ChatCommandService activation_char <char>`. You can also change it by modifying its value inside 
`.../.minecraft/forgehax/config/settings/ChatCommandService.activation_char.json`

**Comment by odies** [comment]
> Yes. In the Input Menu or chat type `ChatCommandService activation_char <char>`. You can also change it by modifying its value inside `.../.minecraft/forgehax/config/settings/ChatCommandService.activation_char.json`

1.16.5 Forge in .../.minecraft/forgehax/config/ no folder wirh name "settings"
