### ISSUE TITLE
ForgeHax-1.16.5-3.3.1-eca8932 does not work

### ISSUE THREAD

**Issue by GreenLass000** [fr1kin/ForgeHax#413]
cache and config folders are generated empty.
I installed last version of forge and don't work
Please need help
I want to use bookbot for automatic book generator

**Comment by fr1kin** [comment]
post latest.log

**Comment by GreenLass000** [comment]
Where can I get the log?

**Comment by GreenLass000** [comment]
Never mind, I already found it
[latest.log](https://github.com/fr1kin/ForgeHax/files/8091105/latest.log)

**Comment by fr1kin** [comment]
I see you have ForgeHax installed, but it never actually loads. Perhaps try using a older version of Forge

**Comment by GreenLass000** [comment]
Ok, before I try it with version 1.16.5-36.2.20, I will try several previous ones and I will tell you if it worked or not

**Comment by fr1kin** [comment]
Try 1.16.5-36.2.2

**Comment by GreenLass000** [comment]
Using version 1.16.5-36.2.2 json files have been created in the config folder, but it still doesn't work when writing to chat:
.bookbot file "test.txt"
I have a file called test.txt in ~/.minecraft/forgehax/
Instead of executing the commands, it appears in the chat as if it were a normal and current comment

Latest.log from ~/.minecraft/logs
[latest.log](https://github.com/fr1kin/ForgeHax/files/8092774/latest.log)

Latest.log from ~/.minecraft/forgehax/logs
[latest.log](https://github.com/fr1kin/ForgeHax/files/8092778/latest.log)

**Comment by GreenLass000** [comment]
I'm starting to think it's a java compatibilities issue, because I have java 8 and java 16 installed at the same time.
I'm going to disable java 16 and try again to see if it works

**Comment by GreenLass000** [comment]
It hasn't worked, I really don't know what else to do
[latest.log](https://github.com/fr1kin/ForgeHax/files/8092847/latest.log)

**Comment by fr1kin** [comment]
Look at #327

**Comment by GreenLass000** [comment]
But my error is not that it does not recognize the command, it is that it is not executed and is sent as if it were a message in the minecraft chat
![chat](https://user-images.githubusercontent.com/69277507/154695417-d7286285-aa60-4152-b11e-cca5e887c540.png)

I have also seen that a message appears saying that I have 0 mods activated, is it possible that this is where the error comes from?
![modsEnabled](https://user-images.githubusercontent.com/69277507/154695584-6fe9248c-1236-42b2-bad8-017bade5fde0.png)

**Comment by fr1kin** [comment]
You don't use chat anymore. Press right shift

**Comment by GreenLass000** [comment]
Woooaa, now it says unknown command, I'm going to #327, thx

**Comment by GreenLass000** [comment]
Working
