### ISSUE TITLE
FORGEHAX CRASHES WENN MOVING ON THE Y AXIS IN MC ETERNAL

### ISSUE THREAD

**Issue by Fjox** [fr1kin/ForgeHax#417]
Hello
So i was tryng to hack with ForgeHax on my friends minecraft server and everytime i move up or down my game crashes
[crash-2022-04-04_11.58.56-client.txt](https://github.com/fr1kin/ForgeHax/files/8408813/crash-2022-04-04_11.58.56-client.txt)
.

**Comment by fr1kin** [comment]
> at net.shadowmage.ancientwarfare.vehicle.input.VehicleInputHandler.handleFireAction

doesn't seem to be caused by forgehax

**Comment by Fjox** [comment]
well it is becaz wen forgehax isnt installed it works

**Comment by fr1kin** [comment]
probably a class patch in that case. i dont maintain 1.12.2 anymore though so gg

**Comment by Fjox** [comment]
thats GAAAAAAYYYYY!!!! 🤣🤣🤣🤣
