### ISSUE TITLE
Forgehax won't load when I launch Minecraft

### ISSUE THREAD

**Issue by An0mal0us** [fr1kin/ForgeHax#424]
I have done everything correct and I have even watched videos on how to install it properly but when I try and load Minecraft, Forgehax won't load with it and I am using forgehax on the latest forge for forge-1.19-41.0.62

**Comment by fr1kin** [comment]
ForgeHax hasn't been updated to 1.17, 1.18, or 1.19 yet

**Comment by An0mal0us** [comment]
I tired 1.16.5 and I still ahd the same problem
