### ISSUE TITLE
Noclip cant go through bedrock 

### ISSUE THREAD

**Issue by InactiveCoyote** [fr1kin/ForgeHax#426]
i was just flying then all of a sudden it teleports me down into bedrock and cant get out noclip dosent work free cam does but can click on anything

**Comment by fr1kin** [comment]
minecraft does some collision checks on the server. if you want to be able to noclip through blocks you need to put yourself in noclip mode on the server side. usually you can do this by close a door on yourself or dropping a sand on yourself
