### ISSUE TITLE
No working commands

### ISSUE THREAD

**Issue by ghost** [fr1kin/ForgeHax#428]
Every time I try to run a command nothing shows up and it does nothing, I tried looking at the ChatIdentifierService.json file but its completely empty. Can you tell me what the problem is?

<img width="428" alt="image" src="https://user-images.githubusercontent.com/111027191/184044637-53c53f01-b7b3-46ac-96f2-bc0d70e0fc2e.png">

**Comment by fr1kin** [comment]
:nauseated_face:
