### ISSUE TITLE
cant hurt entities

### ISSUE THREAD

**Issue by DARKNESS1279** [fr1kin/ForgeHax#430]
forgehax dont allow to right click any entity you can hurt entities only using aimbot

**Comment by DARKNESS1279** [comment]
> forgehax dont allow to right click any entity you can hurt entities only using aimbot

**Comment by fr1kin** [comment]
Yeah it's a known issue related to mouse binds.

**Comment by DARKNESS1279** [comment]
Thx now I can hit mobs

Android için Outlook<https://aka.ms/AAb9ysg> edinin
________________________________
