### ISSUE TITLE
Xray Issue 1.16.5

### ISSUE THREAD

**Issue by PapitaFritaMike** [fr1kin/ForgeHax#440]
I keep on receiving a "NullPointerException" everytime I try to use the xray commands. The only thing that works is "xray enabled 1/0". But other than that, I receive a NullPointerException response. Any ideas?

**Comment by PapitaFritaMike** [comment]
Also markers options is not working and just says "Unknown command" when trying to use or add markers

**Comment by fr1kin** [comment]
at some point the vanilla patch for the xray broke but I never got around to fixing it. but I am unsure if your issue is related. sounds like the module is not loading or you are typing something incorrectly.

**Comment by PapitaFritaMike** [comment]
Yeah I figured it out, since it was a Modded block I was trying to add I had to put the mod before it. Ex: Pixelmon:Sapphire_ore
