### ISSUE TITLE
Some mods will work, after opening and closing the launcher they stop working.

### ISSUE THREAD

**Issue by Tyr4nnic4l** [fr1kin/ForgeHax#45]
One affected mod is Aimbot, after toggling it nothing will happen, but after re opening the launcher multiple times, this seems to be fixed.

**Comment by Tyr4nnic4l** [comment]
Here I have a video demonstrating the lack of function of both aim bot and
no slow during one of these times, if I have some setting wrong then please
tell me. The image is also a picture of the settings that I am using.

Thank you for your time, Ox
 2019-01-01 20-44-07.mp4
<https://drive.google.com/file/d/1Eww_0IhMv7ajHlcxmmhVA5EooY4BE7ND/view?usp=drive_web>

**Comment by fr1kin** [comment]
What other Forge mods are you using? Forgehax and Mixin have a race condition that causes some Forgehax patches to not apply properly. I thought I fixed that though. Make sure you are running the latest version from the jenkins.

**Comment by Tyr4nnic4l** [comment]
Ok, I will do that. Thanks again

**Comment by 0-x-2-2** [comment]
Logs?

**Comment by fr1kin** [comment]
Yeah we need logs and a list of mods you're using

**Comment by Tyr4nnic4l** [comment]
Ok, how do I send logs? Also after downloading the version off of Jenkins
instead of directly from github it is currently working. I am going to
continue using it and see if it continues to work.

**Comment by fr1kin** [comment]
.minecraft/logs/latest.log

**Comment by Tyr4nnic4l** [comment]
Here is the latest log. As for the hacks I was using they were:
Aimbot
AntBats
AutoReconnect
AutoSprint
AutoTotem
Chams
FullBright
GuiMove
Markers
NoSkylightUpdate
NoSlowDown
PortalGui
ShulkerPreview
StorageESP
Tracers
Trajectories

**Comment by 0-x-2-2** [comment]
send debug.log also I don't think you can attach files on github using email.

**Comment by Tyr4nnic4l** [comment]
Is there another way you would want them sent, I can do whatever works best
for you.

**Comment by fr1kin** [comment]
use pastebin or ybin

**Comment by Tyr4nnic4l** [comment]
Here is the paste bin link: https://pastebin.com/JtdjNg38

**Comment by 0-x-2-2** [comment]
Yeah just as fr1kin said it is a race-condition with mixins and his fix failed. Remove the world downloader forge port that I made because liteloader had a issue with future and that is no longer a issue. Just use the most up to date liteloader version from [here](https://github.com/Pokechu22/WorldDownloader/releases).

**Comment by Tyr4nnic4l** [comment]
So that .litemod just goes in my mods folder right?

**Comment by 0-x-2-2** [comment]
I edited the message read github and yes but you need liteloader installed.
