### ISSUE TITLE
Bad local Variable type.

### ISSUE THREAD

**Issue by LameLad007-Sudo** [fr1kin/ForgeHax#450]
Log file will be presented below, version 1.12.2
[latest.log](https://github.com/fr1kin/ForgeHax/files/12565268/latest.log)
The file is a full log, so it should include mods, and the main suspect, I know however the issue is specific to forgehax, as removing it causes minecraft to boot up just fine.

**Comment by fr1kin** [comment]
Yeah its a mod conflict. You could remove the cursed RenderChunk patch and it would fix it.

**Comment by LameLad007-Sudo** [comment]
Well much appreciated, just 1 question for that, bit MC inadept, so I do wish to know how to remove the RenderChunk patch (Or identify what mod has it.)
