### ISSUE TITLE
Failed to initialize in 1.16.5

### ISSUE THREAD

**Issue by Hundreflower11** [fr1kin/ForgeHax#454]
[crash-2024-02-12_20.38.19-fml.txt](https://github.com/fr1kin/ForgeHax/files/14238422/crash-2024-02-12_20.38.19-fml.txt)

**Comment by fr1kin** [comment]
You need to use Java 8

**Comment by Hundreflower11** [comment]
> You need to use Java 8

thanks a lot XD
