### ISSUE TITLE
Cant attack, tried to unbind as said in #197 but cant find any command to do it

### ISSUE THREAD

**Issue by qamwxy** [fr1kin/ForgeHax#455]
Title says it all

**Comment by qamwxy** [comment]
Btw I use 1.16.5

**Comment by qamwxy** [comment]
When tried `Aimbot unbind` the keybind is still here (KEY.KEYBOARD.UNKNOWN)

**Comment by qamwxy** [comment]
And I can only attack when the mob is in far distance

**Comment by fr1kin** [comment]
Yeah its a known issue. The only solution is to unbind everything bound to mouse buttons and restart the game.

**Comment by qamwxy** [comment]
How do I unbind? Because `MOD_NAME unbind` didnt work for the aimbot. And which are binded to by default?

**Comment by fr1kin** [comment]
You just go to the Minecraft control setting tab and it should be under ForgeHax. Find anything under ForgeHax bound to a mouse key and unbind it by pressing the button next to it and pressing escape.
