### ISSUE TITLE
Can't build in intellj idea

### ISSUE THREAD

**Issue by Villygrimm** [fr1kin/ForgeHax#456]
when i build forgehax 2.9.0 for minecraft 1.12.2, i have this error: cannot access AddPlayerData
                            .filter(Objects::nonNull)
bad class file: .gradle\caches\minecraft\net\minecraftforge\forge\1.12.2-14.23.0.2486\snapshot\20170624\forgeBin-1.12.2-14.23.0.2486.jar(net/minecraft/network/play/server/SPacketPlayerListItem$AddPlayerData.class)
bad RuntimeInvisibleParameterAnnotations attribute: AddPlayerData(GameProfile,int,GameType,ITextComponent)
Please remove or make sure it appears in the correct subdirectory of the classpath.

how can i fix it ?

**Comment by fr1kin** [comment]
What JDK version are you using?

**Comment by Villygrimm** [comment]
1.8.0_333

**Comment by fr1kin** [comment]
It built for me just fine. Make sure you are running `./gradlew setupDecompWorkspace` before doing `./gradlew build`

**Comment by Villygrimm** [comment]
I try it later

**Comment by Villygrimm** [comment]
I think I fixed the problem, thanks
