### ISSUE TITLE
Bookbot only does 2 books

### ISSUE THREAD

**Issue by Mobles** [fr1kin/ForgeHax#56]
My issue arrises when running bookbot, it does 2 books then I have to delete the current instance then start again which is tedious, any clue as to why this might be?

All I've done is set my name on the books and everything else is default

**Comment by fr1kin** [comment]
Do you have more than 2 books of worth of text?

**Comment by VanDamonFire** [comment]
ive downloaded the file, where do i get the texts for the Bookbot? im trying to follow your YT Vid and it says Genesis.txt but i dont see that

**Comment by fr1kin** [comment]
you can use any text you desire
