### ISSUE TITLE
Forgehax crashing minecraft when opening minecraft

### ISSUE THREAD

**Issue by AlbertCoolGuy** [fr1kin/ForgeHax#58]
I cant open minecraft when forgehax is installed

Crash report: https://pastebin.com/tRRcEeYi

**Comment by fr1kin** [comment]
You're using an old version of Forgehax (forgehax-1.12-2.2.0-beta.jar). Not much I can do on my side but it looks like you're in luck because its a problem with a dependency. Use the latest forge version for 1.12 and it might work.

**Comment by AlbertCoolGuy** [comment]
You mean the latest Forge 1.12 version?

**Comment by fr1kin** [comment]
Yes
