### ISSUE TITLE
bookbot,dupe - patched???

### ISSUE THREAD

**Issue by Teuhn** [fr1kin/ForgeHax#59]
i've done everything right for the Chunk Dupe glitch. after I made 90 books, (named: 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10) I put in the other 5 books (named: test (for instance)).. I take out the items, relog and just nothing happend.  The chunk didn't go back to it's older state..? 

I followed all these steps: https://pastebin.com/cSrEckee

Is it patched?

**Comment by fr1kin** [comment]
Yes. I believe the Paper Spigot released a patch for 1.13 and 1.12.2 to fix the dupe.

**Comment by VADemon** [comment]
Yes, it depends on the server you're going to use it on. Paper 1.12.2/1.13.2 can be described in two options:

1. Basically prohibited book writing (~10 symbols per page. Hilarious)

2. Did Mojang's work and patched map saving. So everything saves and loads as it should*

Spigot is unaffected, but there's a plugin that prohibits randombook.txt writing. SalC1 should have cited the sources.

**Comment by 0-x-2-2** [comment]
https://github.com/PaperMC/Paper/commit/e8f86cb97d5466c02e9e95384d727d7375c2b695

**Comment by ehsnhxhs** [comment]
Can you book ban yourself by book duping

**Comment by VADemon** [comment]
Depends, try to put 3 in your inventory to find out.
