### ISSUE TITLE
Where do i put the txt file for the bookbot?

### ISSUE THREAD

**Issue by TinyBolts** [fr1kin/ForgeHax#62]
Title says it all. Where do i put the txt file for the bookbot to use?

**Comment by VADemon** [comment]
Where can we put brain for you to use?

https://github.com/fr1kin/ForgeHax/wiki

**Comment by TinyBolts** [comment]
> Where can we put brain for you to use?
> 
> https://github.com/fr1kin/ForgeHax/wiki
> 
> /overreacted

brain.exe stopped working
