### ISSUE TITLE
Using this with 1.13.2

### ISSUE THREAD

**Issue by James94665** [fr1kin/ForgeHax#64]
Is it possible to use this mod with forge 1.13.2 or will a update be released for it?

**Comment by starcraft66** [comment]
Work is currently being undergone to support Minecraft 1.13.2 in the `1.13-wip` branch. It is not quite ready yet but should be soon(tm).

**Comment by JustAnOkapi** [comment]
@fr1kin 	About how long till 1.13.2 is released?

**Comment by babbaj** [comment]
hopefully next week

**Comment by JustAnOkapi** [comment]
Thank you!

**Comment by babbaj** [comment]
nvm already got it working today

**Comment by babbaj** [comment]
latest build on the jenkins should work

**Comment by JustAnOkapi** [comment]
@babbaj 	What's the link? I can't find Jenkins anywhere.

**Comment by VADemon** [comment]
https://jenkins.nhackindustries.com/job/ForgeHax/job/1.13-wip/

**Comment by JustAnOkapi** [comment]
The mod gets loaded into forge but when i type `.help` in chat the mod doesn't work.

**Comment by babbaj** [comment]
youre probably on an old version of forge

**Comment by JustAnOkapi** [comment]
The newer version didn't work either. It didn't even load.

**Comment by 0-x-2-2** [comment]
>newer

you need to be on the latest

**Comment by JustAnOkapi** [comment]
I got it figured out, thanks.
