### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mon4ch** [fr1kin/ForgeHax#66]
I download the zip and can't find the .jar file.

**Comment by mon4ch** [comment]
I tried extracting with 7-zip and Winrar but I still can't get a .jar file.

**Comment by mon4ch** [comment]
I got the .jar and dropped in in a mods folder I had to create and now it wont show up

**Comment by VADemon** [comment]
The .jar isn't there 🙈🙈 it's only the source files (.java) 🙉 "Download" means the project source files on Github 😕

You need to compile it using gradle 😎😎
or download a recent **build** from the 💚 **build**bot. ✔ link is to be found 🔍 in the `Readme.md` 🔎 which is visible on the repository page 📃

"releases" only house very old builds ⌛

**Comment by fr1kin** [comment]
🤡
