### ISSUE TITLE
[PH] File not found

### ISSUE THREAD

**Issue by rey661** [fr1kin/ForgeHax#69]
I followed the tutorial but I couldn't import a file. I named it exactly "first_book.txt" and placed it in the .minecraft/forgehax/. Then in-game I wrote ".bookbot name "My First Book Ever! " (i have only 1 textfile to import) and then ".bookbot start".Then file not found appeared.I'm really sorry I'm new so I don't know most of the stuff.

**Comment by popbob** [comment]
🤡

**Comment by fr1kin** [comment]
https://github.com/fr1kin/ForgeHax/wiki/BookBot

**Comment by fr1kin** [comment]
Since it seems like you actually tried to read the wiki I'll help you. You forgot the step `.bookbot file "first_book.txt"`

**Comment by rey661** [comment]
I tried that too. Still, File not found.
1. .bookbot file "first_book.txt"
 2. .bookbot name "first_book.txt"
3., book bot start
(i got book and quill)
and still, it doesn't work.
I put the text file exactly in the .minecraft/forgehax

**Comment by 0-x-2-2** [comment]
🤡

**Comment by popbob** [comment]
🤢
