### ISSUE TITLE
Unable to hide tick-rate

### ISSUE THREAD

**Issue by Torrbun** [fr1kin/ForgeHax#71]
Hi there, this isn't really a bug, I'd just like a way to be able to hide the tick-rate on the top corner of the screen. 
If it's already an option, then sorry, I can't find it and would like to know how to disable it. Thanks!

**Comment by fr1kin** [comment]
`.activemods tps-meter 0`

**Comment by Torrbun** [comment]
Oh snap! Thanks for the quick reply
