### ISSUE TITLE
Chat command service activation

### ISSUE THREAD

**Issue by CHUMMYBUNS** [fr1kin/ForgeHax#74]
I have aristois hack client enabled and it uses commands with a "." so I went into the forgehax folder and located the chatcommandserviceactivation.json file and changed it to a "," but it still goes back to a period and doesn't work. Can you help me change the activation value/key

**Comment by fr1kin** [comment]
In the Input Menu or chat type `ChatCommandService activation_char <char>`. You can also change it by modifying its value inside
`.../.minecraft/forgehax/config/settings/ChatCommandService.activation_char.json` while the game is not running.

**Comment by CHUMMYBUNS** [comment]
OK the input command worked, thank you so much!!!
