### ISSUE TITLE
How does AutoKey work?

### ISSUE THREAD

**Issue by Orange65** [fr1kin/ForgeHax#77]
I am wondering how to use the hack "auto key". I am trying to get it to click right click however doing .autokey add "right click" "press" does not work. There is nothing on the wiki about it, any help?

**Comment by fr1kin** [comment]
I didn't even know this existed in ForgeHax. I guess Babbaj wrote it, he'd have to tell you what it does and how it works.

**Comment by Orange65** [comment]
> I didn't even know this existed in ForgeHax. I guess Babbaj wrote it, he'd have to tell you what it does and how it works.

Anyway I can contact him easily or get it on the wiki?

**Comment by fr1kin** [comment]
@babbaj
