### ISSUE TITLE
ClientChunkSize missing

### ISSUE THREAD

**Issue by OneCraftDE** [fr1kin/ForgeHax#79]
i cant see the "clientchunksize" module anymore , in an another version on my old pc the module was not missing

**Comment by fr1kin** [comment]
Are you using the latest build from Jenkins?

**Comment by OneCraftDE** [comment]
where is the link to the jenkins

**Comment by fr1kin** [comment]
https://jenkins.nhackindustries.com/job/ForgeHax/job/master/lastSuccessfulBuild/

**Comment by OneCraftDE** [comment]
sorry i used the verison from github

**Comment by babbaj** [comment]
🤡
