### ISSUE TITLE
Player is able to enable fly as if they were in creative mode

### ISSUE THREAD

**Issue by fr1kin** [fr1kin/ForgeHax#82]
Some mod (probably freecam) allows the player to start flying by double jumping (like in creative mod). 99% sure I forgot to allowFlying = false in some mod

**Comment by VADemon** [comment]
yes the one liner check is bugged and leaves you in creative fly mode

**Comment by fr1kin** [comment]
I've been planning on making a fix that will allow other mods to grab a 'handle' to a switch, that way only when all the handles are relinquished will the disable code be allowed to execute.

**Comment by RectangularObject** [comment]
It's FreeCam. I was playing on a survival server and I enabled FreeCam and turned it off and I was still able to fly as if I was in creative.

**Comment by VADemon** [comment]
It was fixed a week ago.
