### ISSUE TITLE
Timer does not save speed when turned on

### ISSUE THREAD

**Issue by EccoMassimo** [fr1kin/ForgeHax#83]
If you type ".timer speed 2" while timer is active, it will set your timer speed, however, if you disable and re-enable the mod, your timer will be set at 1. Typing the command ".timer speed" will return the value of what the timer _should_ be not what it actually is.

**Comment by babbaj** [comment]
fixed in https://github.com/fr1kin/ForgeHax/commit/be5db24f8b2fc91d820851f53b8853dd411ca10b
