### ISSUE TITLE
Any news about the 1.13.2! thanks guys

### ISSUE THREAD

**Issue by iseegr8tfuldeadppl** [fr1kin/ForgeHax#84]
title

**Comment by fr1kin** [comment]
Coremods (something very important for forgehax to function) were redone entirely in 1.13+. We've been waiting for cpw to push his changes that will allow us to use our java based coremods instead of lex's js coremods.

**Comment by babbaj** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/c57c6213ea531aa7f7ef71510b752bd37d1dd608

already have the coremod poz bypass but will require 2 jars

**Comment by iseegr8tfuldeadppl** [comment]
hey thanks for the response guys, btw do u have an idea where you guys will push the 1.13.2 one!

**Comment by fr1kin** [comment]
i only play on 2b2t so until it upgrades to 1.13 or 1.14 we will probably stay on 1.12.2

**Comment by fr1kin** [comment]
1.13.2 release is [here](https://jenkins.nhackindustries.com/job/ForgeHax/job/1.13/)
